<?php
    $HTMLFormID = $this->getHTMLFormID();
    $officeVO = $this->getOfficeVO();
    if($officeVO == null){
    	$officeVO = new Margshri_WebPortal_VO_Master_Office_OfficeVO();
    }
    
    $countryOptions = $this->getCountryOptions();
    $stateOptions   = $this->getStateOptions();
    $districtOptions= $this->getDistrictOptions();
    $cityOptions    = $this->getCityOptions();
    $statusOptions  = $this->getStatusOptions();
    $officeTypeOptions = $this->getOfficeTypeOptions();
    $storeOptions = $this->getStoreOptions();
?>

<script type="text/javascript">
<!--

//SET STATE 
var stateList = '';
var stateOptions = '<?php echo (sizeof($stateOptions) > 0) ?  json_encode($stateOptions) : '' ?>';
if(stateOptions != ''){
	stateList = JSON.parse(stateOptions);	
}

//SET DISTRICT 
var districtList = '';
var districtOptions = '<?php echo (sizeof($districtOptions) > 0) ?  json_encode($districtOptions) : '' ?>';
if(districtOptions != ''){
	districtList = JSON.parse(districtOptions);	
}

//SET STATE 
var cityList = '';
var cityOptions = '<?php echo (sizeof($cityOptions) > 0) ?  json_encode($cityOptions) : '' ?>';
if(cityOptions != ''){
	cityList = JSON.parse(cityOptions);	
}

//SET STATE 
var OFFICEVO  = '';
var officeDTO = '<?php echo ($officeVO->getID() != null) ? json_encode($officeVO->getDataArray()) : '' ?>';
if(officeDTO != ''){
	OFFICEVO = JSON.parse(officeDTO);
}

//-->
</script>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Office</h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
					<tr>
						<td class="label">
							<label for="Value">Name<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="Value" id="Value" 
							value="<?php echo $officeVO->getValue() ?>" 
							class="required-entry input-text" />
						</td>
					</tr>
					
					<tr>
						<td class="label">
							<label for="Code">Code<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="Code" id="Code" 
							value="<?php echo $officeVO->getCode() ?>" 
							class="required-entry input-text" />
						</td>
					</tr>
										 

					<tr>
						<td class="label">
							<label for="TypeID">Office Type<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="TypeID" id="TypeID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($officeTypeOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($officeVO->getTypeID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
						</td>
					</tr>
					
					
					<tr>
						<td class="label">
							<label for="StoreID">Store<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="StoreID" id="StoreID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($storeOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($officeVO->getStoreID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
						</td>
					</tr>
					
					
					<tr>
						<td class="label">
							<label for="Address">Address<span class="required">*</span></label>
						</td>
						<td class="value">
							<textarea rows="3" cols="10" name="Address" id="Address" class="required-entry" style="height: 40px;" ><?php echo $officeVO->getAddress() ?></textarea>
						</td>
					</tr>

					<tr>
						<td class="label">
							<label for="CountryID">Country<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="CountryID" id="CountryID" disabled="disabled">
								<!--  <option>--Select--</option> -->
								<?php foreach ($countryOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" selected="selected"><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td class="label">
							<label for="StateID">State<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="StateID" id="StateID" onchange="formJS.setDistrictList(this.value)" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($stateOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($officeVO->getStateID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value['Name'] ?></option>	
								<?php endforeach; ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td class="label">
							<label for="DistrictID">District<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="DistrictID" id="DistrictID" onchange="formJS.setCityList(this.value)"  class="validate-select">
								<option value="">--Select--</option>
							</select>
						</td>
					</tr>
					
					<tr>
						<td class="label">
							<label for="CityID">City<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="CityID" id="CityID" class="validate-select">
								<option value="">--Select--</option>
							</select>
						</td>
					</tr>
					
					  
					<tr>
						<td class="label">
							<label for="PinCode">PinCode</label>
						</td>
						<td class="value">
							<input type="text" name="PinCode" id="PinCode" 
							value="<?php echo $officeVO->getPinCode() ?>" 
							class="validate-number input-text" />
						</td>
					</tr>
					
					
					<tr>
						<td class="label">
							<label for="StatusID">Status<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="StatusID" id="StatusID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($statusOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($officeVO->getStatusID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
							
							<input type="hidden" id="ID" name="ID" value="<?php echo ($officeVO->getID() > 0) ? $officeVO->getID() : 0 ?>" />
						</td>
					</tr>
					
				</tbody>
			</table>
				
		</div>
	</div>
</div>