<?php
$HTMLFormID = $this->getHTMLFormID();
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            
            <td style="width:50%;"><h3 class="icon-head head-permissions-role"><?php echo ($this->getID() !=null ) ? ($this->__('Edit Office') ) : $this->__('Add Office') ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getBackButtonHtml() ?>
                <?php echo $this->getResetButtonHtml() ?>
                <?php echo $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>

<form action="<?php echo $this->getUrl('*/*/save') ?>" method="post" id="<?php echo $HTMLFormID ?>">
    <?php  echo $this->getBlockHtml('formkey')?>
    <?php  echo $this->getEntropy()?>
</form>

<script type="text/javascript">

function officeVO(){
	this.ID = null;
	this.Value = null;
	this.Code = null;
	this.TypeID = null;
	this.StatusID=null;
	this.Address = ($('Address').value).strip();
	this.CountryID = ($('CountryID').value).strip();
	this.StateID = ($('StateID').value).strip();
	this.DistrictID = ($('DistrictID').value).strip();
	this.CityID = ($('CityID').value).strip();
	this.PinCode = ($('PinCode').value).strip(); 
	
	
}
var newOfficeDTO = new officeVO();

var formObj = new varienForm('<?php echo $HTMLFormID; ?>');
var formJS={

		submit : function(){
    		if(!formJS.saveValidation()) return ;
				formJS.saveAjax();
		},

		saveValidation : function(){
			var errorMsg = '';
         	if(!(formObj.validator && formObj.validator.validate())){
    	    	return false;
	    	}

         	// SET VOs 
         	newOfficeDTO.ID = ($('ID').value).strip();
         	newOfficeDTO.Value = ($('Value').value).strip();
         	newOfficeDTO.Code = ($('Code').value).strip();
         	newOfficeDTO.TypeID = ($('TypeID').value).strip();
         	newOfficeDTO.StoreID = ($('StoreID').value).strip();
         	newOfficeDTO.StatusID = ($('StatusID').value).strip();

         	newOfficeDTO.Address = ($('Address').value).strip();
         	newOfficeDTO.CountryID = ($('CountryID').value).strip();
         	newOfficeDTO.StateID = ($('StateID').value).strip();
         	newOfficeDTO.DistrictID = ($('DistrictID').value).strip();
         	newOfficeDTO.CityID = ($('CityID').value).strip();
         	newOfficeDTO.PinCode = ($('PinCode').value).strip(); 
         	
         	if(errorMsg != ''){
            	alert(errorMsg);
				return false;
			}

			return true;	
		},	

        saveAjax: function(){
        	var URL = "<?php echo $this->getUrl('*/*/save')?>" ;
		    var parameters= {"OfficeDataObj": JSON.stringify(newOfficeDTO,null) };
		    var callBackMethod ="formJS.responseSave";
		    var callBackArgs =null;
		    ajaxRequest.execute(	URL, parameters, callBackMethod , callBackArgs );
		    return false;
     	},

	    responseSave : function(response,args) {
        	if(response.SuccessMessage !=null){
			 	window.location.href = "<?php echo $this->getUrl('*/*/index')?>";
			 	return;
			}else if(response.ErrorMessage !=null){
				alert(response.ErrorMessage);
    			return false;
 			}
 	 	},


		setDistrictList: function(stateID){
			//var stateID = obj.value;
			var innerHTML = '<option value="">--Select--</option>';
			for(var key in districtList){
				if(districtList[key].StateID == stateID){
					if(key == OFFICEVO.DistrictID)
						innerHTML += '<option value="'+key+'" selected = "selected">'+districtList[key].Name+'</option>';
					else
						innerHTML += '<option value="'+key+'">'+districtList[key].Name+'</option>';	
				}
			}
			UI.elementDisabled($('DistrictID'), false);
			$('DistrictID').innerHTML = innerHTML;
			return; 
		},

		setCityList: function(districtID){
			//var districtID = obj.value;
			var innerHTML = '<option value="">--Select--</option>';
			for(var key in cityList){
				if(cityList[key].DistrictID == districtID){
					if(key == OFFICEVO.CityID)
						innerHTML += '<option value="'+key+'" selected = "selected">'+cityList[key].Name+'</option>';
					else		
						innerHTML += '<option value="'+key+'">'+cityList[key].Name+'</option>';
				}
			}
			UI.elementDisabled($('CityID'), false);
			$('CityID').innerHTML = innerHTML;
			return; 
		},

		defaultSetting: function(){
			UI.elementDisabled($('DistrictID'), true);
			UI.elementDisabled($('CityID'), true);
		}
};

//FOR EDIT 
if(OFFICEVO != ''){
	formJS.setDistrictList(OFFICEVO.StateID);
	formJS.setCityList(OFFICEVO.DistrictID);		
	
}else{
	formJS.defaultSetting();
}


</script>