<?php
	
    $HTMLFormID = $this->getHTMLFormID();
    $bloodDonorVO = $this->getBloodDonorVO();    
    
    if($bloodDonorVO == null){
    	$bloodDonorVO = new Margshri_WebPortal_VO_Center_Content_Type2_BloodDonor_BloodDonorVO();
    }
    
    $statusOptions = $this->getStatusOptions();
    $bloodGroupOptions = $this->getBloodGroupOptions();
    $isDonatedOptions = $this->getIsDonatedOptions();
?>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__("Blood Donor") ?></h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
	   		<table class="form-list">
				<tbody>

				
					<tr>
						<td class="label">
							<label for="CustomerName">Customer Name</label>
						</td>
						<td class="label">
							<label for="CustomerName"><?php echo $bloodDonorVO->getFirstName() . " " . $bloodDonorVO->getLastName() ?></label>
						</td>
					</tr>

					<tr>
						<td class="label">
							<label for="IsDonated">Is Donated</label>
						</td>
						<td class="label">
							<select name="IsDonated" id="IsDonated" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($isDonatedOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($bloodDonorVO->getIsDonated() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td class="label">
							<label for="LastDonatedAt">Last Donated Date</label>
						</td>
						<td class="value"><input id="LastDonatedAt"
							name="LastDonatedAt" readonly="readonly"
							value="<?php echo ($bloodDonorVO->getLastDonatedAt() != '0000-00-00 00:00:00') ? $bloodDonorVO->getLastDonatedAt() : ""  ?>"
							class="input-text" style="width: 175px;"
							type="text" /> <img
							src="<?php  echo Mage::getDesign()->getSkinUrl('images/grid-cal.gif') ?>"
							alt="" class="v-middle" id="LastDonatedAtIMG"
							title="Select Date" style=""> 
							<script type="text/javascript">
		                                 //<![CDATA[
		                                 document.getElementById('LastDonatedAt').addEventListener('keypress', function(event) {
										        if (event.keyCode == 13) {
										            event.preventDefault();
										        }
										 });
										  
		                                 Calendar.setup({
		                                                  inputField: "LastDonatedAt",
		                                                  ifFormat: "%Y-%m-%d %H:%M:%S",
		                                                  showsTime: 12,
		                                                  button: "LastDonatedAtIMG",
		                                                  align: "Bl",
		                                                  onClose   : function() { this.hide(); },
		                                                  singleClick : true
		                                               });
                                        //]]> 
                                    </script>
						</td>
					</tr>
							
							
										
					
					<tr>
						<td class="label">
							<label for="StatusID">Status<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="StatusID" id="StatusID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($statusOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($bloodDonorVO->getStatusID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
							<input type="hidden" id="CustomerID" name="CustomerID" value="<?php echo $bloodDonorVO->getCustomerID() ?>">
							<input type="hidden" id="ID" name="ID" value="<?php echo ($bloodDonorVO->getID() != null) ? $bloodDonorVO->getID() : 0  ?>">
						</td>
					</tr>
					
					
					<tr>
						<td class="label">
							<label for="BloodGroup">Blood Group<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="BloodGroupID" id="BloodGroupID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($bloodGroupOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($bloodDonorVO->getBloodGroupID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
						</td>
					</tr>
					
					
					
				</tbody>
			</table>  		
		</div>
	</div>
</div>