<?php
    $HTMLFormID = $this->getHTMLFormID();
    $entityVO = $this->getEntityVO();
    $statusOptions  = $this->getStatusOptions();
    $typeOptions = $this->getTypeOptions();
    if($entityVO == null){
    	$entityVO = new Margshri_WebPortal_VO_Master_SubPage_EntityVO();
    }
?>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Sub Page Entity</h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
					<tr>
						<td class="label">
							<label for="Value">Name<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="Value" id="Value" 
							value="<?php echo $entityVO->getValue() ?>" 
							class="required-entry input-text" />
						</td>
					</tr>
					
					<tr>
						<td class="label">
							<label for="TableCode">Table Code<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="TableCode" id="TableCode" 
							value="<?php echo $entityVO->getTableCode() ?>" 
							class="required-entry input-text" />
						</td>
					</tr>
					
					  
					<tr>
						<td class="label">
							<label for="TypeID">Type<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="TypeID" id="TypeID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($typeOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($entityVO->getTypeID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
							
						</td>
					</tr>
					
					
					<tr>
						<td class="label">
							<label for="StatusID">Status<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="StatusID" id="StatusID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($statusOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($entityVO->getStatusID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
							
							<input type="hidden" id="ID" name="ID" value="<?php echo ($entityVO->getID() > 0) ? $entityVO->getID() : 0 ?>" />
						</td>
					</tr>
					
				</tbody>
			</table>
				
				 
		</div>
	</div>
</div>