<?php
	
    $HTMLFormID = $this->getHTMLFormID();
    $advertisementVO    = $this->getAdvertisementVO();    
    
    if($advertisementVO == null){
    	$advertisementVO = new Margshri_WebPortal_VO_FileUpload_ImageUpload_AdvertisementVO();
    }
    
    $countryOptions = $this->getCountryOptions();
    $stateOptions   = $this->getStateOptions();
    $districtOptions= $this->getDistrictOptions();
    $cityOptions    = $this->getCityOptions();
    $statusOptions  = $this->getStatusOptions();
    $advertisementTypeOptions = $this->getAdvertisementTypeOptions();
    
    $tableCodeOptions = $this->getTableCodeOptions();
    $orderOptions = $this->getOrderOptions();
    
    
    
    
    
    
    
?>
<script type="text/javascript">
<!--

//SET STATE 
var stateList = '';
var stateOptions = '<?php echo (sizeof($stateOptions) > 0) ?  json_encode($stateOptions) : '' ?>';
if(stateOptions != ''){
	stateList = JSON.parse(stateOptions);	
}

//SET DISTRICT 
var districtList = '';
var districtOptions = '<?php echo (sizeof($districtOptions) > 0) ?  json_encode($districtOptions) : '' ?>';
if(districtOptions != ''){
	districtList = JSON.parse(districtOptions);	
}

//SET STATE 
var cityList = '';
var cityOptions = '<?php echo (sizeof($cityOptions) > 0) ?  json_encode($cityOptions) : '' ?>';
if(cityOptions != ''){
	cityList = JSON.parse(cityOptions);	
}

//SET STATE 
var ADVERTISEMENTVO  = '';
var advertisementDTO = '<?php echo ($advertisementVO->getID() != null) ? json_encode($advertisementVO->getDataArray()) : '' ?>';
if(advertisementDTO != ''){
	ADVERTISEMENTVO = JSON.parse(advertisementDTO);
}

//-->
</script>


<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__("Image Upload") ?></h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
		  <table style="">
		  	<tr>
		  		<td>
		  			<table class="form-list">
						<tbody>
							<tr>
								<td class="label">
									<label for="Value">Name<span class="required">*</span></label>
								</td>
								<td class="value">
									<input type="text" name="Value" id="Value" 
									value="<?php echo $advertisementVO->getValue() ?>" 
									class="required-entry input-text" />
								</td>
							</tr>
							
							<!--  
							<tr>
								<td class="label">
									<label for="Code">Code<span class="required">*</span></label>
								</td>
								<td class="value">
									<input type="text" name="Code" id="Code" 
									value="<?php echo $advertisementVO->getCode() ?>" 
									class="required-entry input-text" />
								</td>
							</tr>
							-->
							
							<tr>
								<td class="label">
									<label for="Address">Address<span class="required">*</span></label>
								</td>
								<td class="value">
									<textarea rows="3" cols="10" name="Address" id="Address" class="required-entry" style="height: 40px;" ><?php echo $advertisementVO->getAddress() ?></textarea>
								</td>
							</tr>
		
							<tr>
								<td class="label">
									<label for="CountryID">Country<span class="required">*</span></label>
								</td>
								<td class="value">
									<select name="CountryID" id="CountryID" disabled="disabled">
										<!--  <option>--Select--</option> -->
										<?php foreach ($countryOptions as $key=>$value): ?>
											<option value="<?php echo $key ?>" selected="selected"><?php echo $value ?></option>	
										<?php endforeach; ?>
									</select>
								</td>
							</tr>
							
							<tr>
								<td class="label">
									<label for="StateID">State</label>
								</td>
								<td class="value">
									<select name="StateID" id="StateID" onchange="formJS.setDistrictList(this.value)">
										<option value="">--Select--</option>
										<?php foreach ($stateOptions as $key=>$value): ?>
											<option value="<?php echo $key ?>" <?php echo ($advertisementVO->getStateID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value['Name'] ?></option>	
										<?php endforeach; ?>
									</select>
								</td>
							</tr>
							
							<tr>
								<td class="label">
									<label for="DistrictID">District</label>
								</td>
								<td class="value">
									<select name="DistrictID" id="DistrictID" onchange="formJS.setCityList(this.value)" >
										<option value="">--Select--</option>
									</select>
								</td>
							</tr>
							
							<!-- class="validate-select" -->
							
							<tr>
								<td class="label">
									<label for="CityID">City</label>
								</td>
								<td class="value">
									<select name="CityID" id="CityID">
										<option value="">--Select--</option>
									</select>
								</td>
							</tr>
							
							  
							<tr>
								<td class="label">
									<label for="PinCode">PinCode</label>
								</td>
								<td class="value">
									<input type="text" name="PinCode" id="PinCode" 
									value="<?php echo $advertisementVO->getPinCode() ?>" 
									class="validate-number input-text" />
								</td>
							</tr>
							
							<!--  
							<tr>
								<td class="label">
									<label for="Category1ID">First Category Name</label>
								</td>
								<td class="value">
									<select name="Category1ID" id="Category1ID" onchange="formJS.setCategoryBox(this)" >
										<option value="">--Select--</option>
										<?php foreach ($dynamicColumnOptions as $key=>$value): ?>
											<option value="<?php echo $key ?>" <?php echo ($advertisementVO->getCategory1ID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value['Value'] ?></option>	
										<?php endforeach; ?>
									</select>
									
									<input type="text" name="Category1Value" id="Category1Value"  
									value="<?php echo $advertisementVO->getCategory1Value() ?>" 
									class="input-text" style="margin-top: 10px;" />
								</td>
							</tr>
							

							<tr>
								<td class="label">
									<label for="Category2ID">Second Category Name</label>
								</td>
								<td class="value">
									<select name="Category2ID" id="Category2ID" onchange="formJS.setCategoryBox(this)" >
										<option value="">--Select--</option>
										<?php foreach ($dynamicColumnOptions as $key=>$value): ?>
											<option value="<?php echo $key ?>" <?php echo ($advertisementVO->getCategory2ID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value['Value'] ?></option>	
										<?php endforeach; ?>
									</select>
									<input type="text" name="Category2Value" id="Category2Value"  
									value="<?php echo $advertisementVO->getCategory2Value() ?>" 
									class="input-text" style="margin-top: 10px;" />
								</td>
							</tr>
							
							
							
							<tr>
								<td class="label">
									<label for="Category3ID">Third Category Name</label>
								</td>
								<td class="value">
									<select name="Category3ID" id="Category3ID" onchange="formJS.setCategoryBox(this)" >
										<option value="">--Select--</option>
										<?php foreach ($dynamicColumnOptions as $key=>$value): ?>
											<option value="<?php echo $key ?>" <?php echo ($advertisementVO->getCategory3ID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value['Value'] ?></option>	
										<?php endforeach; ?>
									</select>
									<input type="text" name="Category3Value" id="Category3Value"  
									value="<?php echo $advertisementVO->getCategory3Value() ?>" 
									class="input-text" style="margin-top: 10px;" />
								</td>
							</tr>
							
							-->
							
							<tr>
								<td class="value" colspan="2">
									<div style="border: 1px solid; border-color: #AAA #C8C8C8 #C8C8C8 #AAA;">
										<img id="Preview" alt="Image" src="<?php echo ($advertisementVO->getImagePath() != null && $advertisementVO->getImagePath() != '' )  ?  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $advertisementVO->getImagePath() : '' ?>"  width="487px" height="162px" style="border-style: hidden;"/>
										<input type="file" id="Image" name="Image" onchange="return formJS.getFilePath()" style="display: none;" />
								   	</div>
							   	</td>
							</tr>
							
							<tr>
								<td class="value" colspan="2" style="text-align: right;">
									<button type="button" id="Browse" name="Browse" onclick="return formJS.browseImageFile()" >Browse</button>
								</td>
							</tr>							
							
	
							
						</tbody>
					</table>		
		  		</td>	
		  	
		  		<td style="width: 200px;"></td>
		  	
		  		<td>
					<table class="form-list">
						<tbody>

							<!--  
							<tr>
								<td class="label">
									<label for="TinNumber">Registration No.</label>
								</td>
								<td class="value">
									<input type="text" name="TinNumber" id="TinNumber" 
									value="<?php echo $advertisementVO->getTinNumber() ?>" 
									class="input-text" />
								</td>
							</tr>
							
							
							<tr>
								<td class="label">
									<label for="PANNumber">Pan No.</label>
								</td>
								<td class="value">
									<input type="text" name="PANNumber" id="PANNumber" 
									value="<?php echo $advertisementVO->getPANNumber() ?>" 
									class="input-text" />
								</td>
							</tr>
						
						
							<tr>
								<td class="label">
									<label for="LandLineNumber">Land Line Number</label>
								</td>
								<td class="value">
									<input type="text" name="LandLineNumber" id="LandLineNumber" 
									value="<?php echo $advertisementVO->getLandLineNumber() ?>" 
									class="validate-phoneLax input-text" />
								</td>
							</tr>
							-->
							
							
							<tr>
								<td class="label">
									<label for="WebsiteLink">Website Link</label>
								</td>
								<td class="value">
									<input type="text" name="WebsiteLink" id="WebsiteLink" 
									value="<?php echo $advertisementVO->getWebsiteLink() ?>" 
									class="input-text" />
								</td>
							</tr>
						
						
							<tr>
								<td class="label">
									<label for="MobileNumber1">Mobile Number</label>
								</td>
								<td class="value">
									<input type="text" name="MobileNumber1" id="MobileNumber1" 
									value="<?php echo $advertisementVO->getMobileNumber1() ?>" 
									class="input-text validate-mobileno" />
								</td>
							</tr>
							
							<!--  
							<tr>
								<td class="label">
									<label for="MobileNumber2">Mobile Number 2</label>
								</td>
								<td class="value">
									<input type="text" name="MobileNumber2" id="MobileNumber2" 
									value="<?php echo $advertisementVO->getMobileNumber2() ?>" 
									class="input-text validate-mobileno" />
								</td>
							</tr>
									
									
							<tr>
								<td class="label">
									<label for="Email">Email</label>
								</td>
								<td class="value">
									<input type="text" name="Email" id="Email" 
									value="<?php echo $advertisementVO->getEmail() ?>" 
									class="validate-email input-text" />
								</td>
							</tr>
							-->	

							<tr>
								<td class="label">
									<label for="TypeID">Advertisement Type<span class="required">*</span></label>
								</td>
								<td class="value">
									<select name="TypeID" id="TypeID" class="validate-select">
										<option value="">--Select--</option>
										<?php foreach ($advertisementTypeOptions as $key=>$value): ?>
											<option value="<?php echo $key ?>" <?php echo ($advertisementVO->getTypeID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value ?></option>	
										<?php endforeach; ?>
									</select>
								</td>
							</tr>
							
							<tr>
								<td class="label">
									<label for="Order">Order<span class="required">*</span></label>
								</td>
								<td class="value">
									<select name="Order" id="Order" class="validate-select">
										<option value="">--Select--</option>
										<?php foreach ($orderOptions as $key=>$value): ?>
											<option value="<?php echo $key ?>" <?php echo ($advertisementVO->getOrder() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value ?></option>	
										<?php endforeach; ?>
									</select>
								</td>
							</tr>
							

							<tr>
								<td class="label">
									<label for="TableCode">Page<span class="required">*</span></label>
								</td>
								<td class="value">
									<select name="TableCode" id="TableCode" class="validate-select">
										<option value="">--Select--</option>
										<?php foreach ($tableCodeOptions as $key=>$value): ?>
											<option value="<?php echo $key ?>" <?php echo ($advertisementVO->getTableCode() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value ?></option>	
										<?php endforeach; ?>
									</select>
								</td>
							</tr>
							
							
							<tr>
								<td class="label"><label for="LaunchDate">Launch Date<span
										class="required">*</span>
								</label>
								</td>
								<td class="value"><input id="LaunchDate"
									name="LaunchDate" readonly="readonly"
									value="<?php echo $advertisementVO->getLaunchDate() ?>"
									class="required-entry input-text" style="width: 175px;"
									type="text" /> <img
									src="<?php  echo Mage::getDesign()->getSkinUrl('images/grid-cal.gif') ?>"
									alt="" class="v-middle" id="LaunchDateIMG"
									title="Select Date" style=""> 
									<script type="text/javascript">
		                                 //<![CDATA[ 
		                                 Calendar.setup({
		                                                  inputField: "LaunchDate",
		                                                  ifFormat: "%Y-%m-%d %H:%M:%S",
		                                                  showsTime: 12,
		                                                  button: "LaunchDateIMG",
		                                                  align: "Bl",
		                                                  onClose   : function() { this.hide(); return validationControl.dateTime(); },
		                                                  singleClick : true
		                                               });
                                        //]]> 
                                    </script>
								</td>	
							</tr>	
							
							<tr>
								<td class="label"><label for="EndDate">End Date<span
										class="required">*</span>
								</label>
								</td>
								<td class="value"><input id="EndDate"
									name="EndDate" readonly="readonly"
									value="<?php echo $advertisementVO->getEndDate() ?>"
									class="required-entry input-text" style="width: 175px;"
									type="text" /> <img
									src="<?php  echo Mage::getDesign()->getSkinUrl('images/grid-cal.gif') ?>"
									alt="" class="v-middle" id="EndDateIMG"
									title="Select Date" style=""> 
									<script type="text/javascript">
		                                 //<![CDATA[ 
		                                 Calendar.setup({
		                                                  inputField: "EndDate",
		                                                  ifFormat: "%Y-%m-%d %H:%M:%S",
		                                                  showsTime: 12,
		                                                  button: "EndDateIMG",
		                                                  align: "Bl",
		                                                  onClose   : function() { this.hide(); return validationControl.dateTime(); },
		                                                  singleClick : true
		                                               });
                                        //]]> 
                                    </script>
								</td>	
							</tr>	
							
							
							<tr>
								<td class="label">
									<label for="StatusID">Status<span class="required">*</span></label>
								</td>
								<td class="value">
									<select name="StatusID" id="StatusID" class="validate-select">
										<option value="">--Select--</option>
										<?php foreach ($statusOptions as $key=>$value): ?>
											<option value="<?php echo $key ?>" <?php echo ($advertisementVO->getStatusID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value ?></option>	
										<?php endforeach; ?>
									</select>
									<input type="hidden" id="ID" name="ID" value="<?php echo ($advertisementVO->getID() != null) ? $advertisementVO->getID() : 0  ?>">
								</td>
							</tr>
							
							
							<tr>
								<td class="label">
									<label for="IsTemp">Is Temp (Temporary Advertisement)</label>
								</td>
								<td class="value">
									<input type="checkbox" name="IsTemp" id="IsTemp" <?php echo ($advertisementVO->getIsTemp() == 1) ? "checked = 'checked'" : '' ?>>
								</td>
							</tr>
							
						</tbody>
					</table>  		
		  		</td>
		  	</tr>
		  </table>
			
		</div>
	</div>
</div>