<?php
	
    $HTMLFormID = $this->getHTMLFormID();
    //$title    = $this->__(ucwords( str_replace('apctweb', '',$this->getTableCode())) ) ;
    $title      = Mage::helper('webportal/Data')->getPageTitleByTableCode($this->getTableCode());
     
    
    $type8VO    = $this->getType8VO();    
    
    if($type8VO == null){
    	$type8VO = new Margshri_WebPortal_VO_Center_Content_Type8_Type8VO($this->getTableCode());
    }
    
    $countryOptions = $this->getCountryOptions();
    $stateOptions   = $this->getStateOptions();
    $districtOptions= $this->getDistrictOptions();
    $cityOptions    = $this->getCityOptions();
    $statusOptions  = $this->getStatusOptions();
    $dynamicColumnOptions = $this->getDynamicColumnOptions();
    $tableVOs = $this->getTableVOs();
    $redirectURL    = '*/*/'. $this->getTableCode();
    
    
    
    $tableOptions = array();
    foreach ($tableVOs as $tableVO){
    	$tableOptions[$tableVO->getCode()] = $tableVO->getCode();  
    }
?>
<script type="text/javascript">
<!--

//SET STATE 
var stateList = '';
var stateOptions = '<?php echo (sizeof($stateOptions) > 0) ?  json_encode($stateOptions) : '' ?>';
if(stateOptions != ''){
	stateList = JSON.parse(stateOptions);	
}

//SET DISTRICT 
var districtList = '';
var districtOptions = '<?php echo (sizeof($districtOptions) > 0) ?  json_encode($districtOptions) : '' ?>';
if(districtOptions != ''){
	districtList = JSON.parse(districtOptions);	
}

//SET STATE 
var cityList = '';
var cityOptions = '<?php echo (sizeof($cityOptions) > 0) ?  json_encode($cityOptions) : '' ?>';
if(cityOptions != ''){
	cityList = JSON.parse(cityOptions);	
}

//SET STATE 
var TYPE8VO  = '';
var type8DTO = '<?php echo ($type8VO->getID() != null) ? json_encode($type8VO->getDataArray()) : '' ?>';
if(type8DTO != ''){
	TYPE8VO = JSON.parse(type8DTO);
}


//SET TABLE VOs 
var tableList  = '';
var tableOptions = '<?php echo (sizeof($tableOptions) > 0) ? json_encode($tableOptions) : '' ?>';
if(tableOptions != ''){
	tableList = JSON.parse(tableOptions);
}



var REDIRECTURL = '<?php echo $this->getUrl($redirectURL) ?>';



//-->
</script>


<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $title ?></h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
		  <table>
		  	<tr>
		  		<td>
		  			<table class="form-list">
						<tbody>
							<tr>
								<td class="label">
									<label for="Value">Name<span class="required">*</span></label>
								</td>
								<td class="value">
									<input type="text" name="Value" id="Value" 
									value="<?php echo $type8VO->getValue() ?>" 
									class="required-entry input-text" />
								</td>
							</tr>
							
							
							<tr>
								<td class="label">
									<label for="Address">Address<span class="required">*</span></label>
								</td>
								<td class="value">
									<textarea rows="3" cols="10" name="Address" id="Address" class="required-entry" style="height: 40px;" ><?php echo $type8VO->getAddress() ?></textarea>
								</td>
							</tr>
		
							<tr>
								<td class="label">
									<label for="CountryID">Country<span class="required">*</span></label>
								</td>
								<td class="value">
									<select name="CountryID" id="CountryID" disabled="disabled">
										<!--  <option>--Select--</option> -->
										<?php foreach ($countryOptions as $key=>$value): ?>
											<option value="<?php echo $key ?>" selected="selected"><?php echo $value ?></option>	
										<?php endforeach; ?>
									</select>
								</td>
							</tr>
							
							<tr>
								<td class="label">
									<label for="StateID">State<span class="required">*</span></label>
								</td>
								<td class="value">
									<select name="StateID" id="StateID" onchange="formJS.setDistrictList(this.value)" class="validate-select">
										<option value="">--Select--</option>
										<?php foreach ($stateOptions as $key=>$value): ?>
											<option value="<?php echo $key ?>" <?php echo ($type8VO->getStateID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value['Name'] ?></option>	
										<?php endforeach; ?>
									</select>
								</td>
							</tr>
							
							<tr>
								<td class="label">
									<label for="DistrictID">District<span class="required">*</span></label>
								</td>
								<td class="value">
									<select name="DistrictID" id="DistrictID" onchange="formJS.setCityList(this.value)"  class="validate-select">
										<option value="">--Select--</option>
									</select>
								</td>
							</tr>
							
							<tr>
								<td class="label">
									<label for="CityID">City<span class="required">*</span></label>
								</td>
								<td class="value">
									<select name="CityID" id="CityID" class="validate-select">
										<option value="">--Select--</option>
									</select>
								</td>
							</tr>
							
							  
							<tr>
								<td class="label">
									<label for="PinCode">Pin Code</label>
								</td>
								<td class="value">
									<input type="text" name="PinCode" id="PinCode" 
									value="<?php echo $type8VO->getPinCode() ?>" 
									class="validate-number input-text" />
								</td>
							</tr>
							
							
							<tr>
								<td class="label">
									<label for="Category1ID">First Category Name</label>
								</td>
								<td class="value">
									<select name="Category1ID" id="Category1ID" onchange="formJS.setCategoryBox(this)" >
										<option value="">--Select--</option>
										<?php foreach ($dynamicColumnOptions as $key=>$value): ?>
											<option value="<?php echo $key ?>" <?php echo ($type8VO->getCategory1ID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value['Value'] ?></option>	
										<?php endforeach; ?>
									</select>
									
									<input type="text" name="Category1Value" id="Category1Value"  
									value="<?php echo $type8VO->getCategory1Value() ?>" 
									class="input-text" style="margin-top: 10px;" />
								</td>
							</tr>
							

							<tr>
								<td class="label">
									<label for="Category2ID">Second Category Name</label>
								</td>
								<td class="value">
									<select name="Category2ID" id="Category2ID" onchange="formJS.setCategoryBox(this)" >
										<option value="">--Select--</option>
										<?php foreach ($dynamicColumnOptions as $key=>$value): ?>
											<option value="<?php echo $key ?>" <?php echo ($type8VO->getCategory2ID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value['Value'] ?></option>	
										<?php endforeach; ?>
									</select>
									<input type="text" name="Category2Value" id="Category2Value"  
									value="<?php echo $type8VO->getCategory2Value() ?>" 
									class="input-text" style="margin-top: 10px;" />
								</td>
							</tr>
							
							
							
							<tr>
								<td class="label">
									<label for="Category3ID">Third Category Name</label>
								</td>
								<td class="value">
									<select name="Category3ID" id="Category3ID" onchange="formJS.setCategoryBox(this)" >
										<option value="">--Select--</option>
										<?php foreach ($dynamicColumnOptions as $key=>$value): ?>
											<option value="<?php echo $key ?>" <?php echo ($type8VO->getCategory3ID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value['Value'] ?></option>	
										<?php endforeach; ?>
									</select>
									<input type="text" name="Category3Value" id="Category3Value"  
									value="<?php echo $type8VO->getCategory3Value() ?>" 
									class="input-text" style="margin-top: 10px;" />
								</td>
							</tr>
							
							  
							
	
							
						</tbody>
					</table>		
		  		</td>	
		  	
		  		<td style="width: 200px;"></td>
		  	
		  		<td>
					<table class="form-list">
						<tbody>

							<tr>
								<td class="label">
									<label for="TinNumber">Registration No.</label>
								</td>
								<td class="value">
									<input type="text" name="TinNumber" id="TinNumber" 
									value="<?php echo $type8VO->getTinNumber() ?>" 
									class="input-text" />
								</td>
							</tr>
							
							
							<tr>
								<td class="label">
									<label for="PANNumber">PAN No.</label>
								</td>
								<td class="value">
									<input type="text" name="PANNumber" id="PANNumber" 
									value="<?php echo $type8VO->getPANNumber() ?>" 
									class="input-text" />
								</td>
							</tr>
							
						
							<tr>
								<td class="label">
									<label for="WebsiteLink">Website Link</label>
								</td>
								<td class="value">
									<input type="text" name="WebsiteLink" id="WebsiteLink" 
									value="<?php echo $type8VO->getWebsiteLink() ?>" 
									class="input-text" />
								</td>
								
								<!-- validate-clean-url -->
							</tr>
							
						
						
						
							<tr>
								<td class="label">
									<label for="LandLineNumber">Land Line Number</label>
								</td>
								<td class="value">
									<input type="text" name="LandLineNumber" id="LandLineNumber" 
									value="<?php echo $type8VO->getLandLineNumber() ?>" 
									class="validate-phoneLax input-text" />
								</td>
							</tr>
							
							
							<tr>
								<td class="label">
									<label for="MobileNumber1">Mobile Number 1</label>
								</td>
								<td class="value">
									<input type="text" name="MobileNumber1" id="MobileNumber1" 
									value="<?php echo $type8VO->getMobileNumber1() ?>" 
									class="input-text validate-mobileno" />
								</td>
							</tr>
							
							
							<tr>
								<td class="label">
									<label for="MobileNumber2">Mobile Number 2</label>
								</td>
								<td class="value">
									<input type="text" name="MobileNumber2" id="MobileNumber2" 
									value="<?php echo $type8VO->getMobileNumber2() ?>" 
									class="input-text validate-mobileno" />
								</td>
							</tr>
									
									
							<tr>
								<td class="label">
									<label for="Email">Email</label>
								</td>
								<td class="value">
									<input type="text" name="Email" id="Email" 
									value="<?php echo $type8VO->getEmail() ?>" 
									class="validate-email input-text" />
								</td>
							</tr>	
						
						
							<tr>
								<td class="label">
									<label for="StatusID">Status<span class="required">*</span></label>
								</td>
								<td class="value">
									<select name="StatusID" id="StatusID" class="validate-select">
										<option value="">--Select--</option>
										<?php foreach ($statusOptions as $key=>$value): ?>
											<option value="<?php echo $key ?>" <?php echo ($type8VO->getStatusID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value ?></option>	
										<?php endforeach; ?>
									</select>
									
									<input type="hidden" id="ID" name="ID" value="<?php echo ($type8VO->getID() != null) ? $type8VO->getID() : 0  ?>">
									<input type="hidden" id="TableName" name="TableName" value="<?php echo $this->getTableCode()  ?>">
								</td>
							</tr>
		
		
							<tr>
								<td class="label">
									<label for="IsPaid">Is Paid (Sub Page)</label>
								</td>
								<td class="value">
									<input type="checkbox" name="IsPaid" id="IsPaid" <?php echo ($type8VO->getIsPaid() == 1) ? "checked = 'checked'" : '' ?>>
								</td>
							</tr>
							
							
							
							
						</tbody>
					</table>  		
		  		</td>
		  	</tr>
		  	
		  </table>
			
		</div>
	</div>
</div>	
	
<div class="entry-edit">	
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend"><?php echo 'Choose File For Multipal Entry' ?></h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
			<table>
				<tr>
			  		<td colspan="3">	
			  			<table class="form-list">
							<tbody>
								<tr>
							  		<?php $totalRows = sizeof($tableVOs) ?>
							  		<?php $totalCount= 0; ?>
							  		<?php $rowCount = 1; ?>
							  		<?php /* @var $tableVO Margshri_WebPortal_VO_Master_Table_TableVO */  ?>
						  			<?php foreach ($tableVOs as $tableVO): ?>
						  				<?php $totalCount++ ?>
						  				<?php if($rowCount == 1): ?>
						  						<td >
						  				<?php endif; ?>
						  						<input type="checkbox" name="<?php echo $tableVO->getCode() ?>" id="<?php echo $tableVO->getCode() ?>" 
						  						value="<?php echo $tableVO->getCode() ?>" <?php echo ($tableVO->getCode() == $this->getTableCode()) ? "checked = 'checked' disabled = disabled " : ""  ?> ><?php echo $tableVO->getFileName() ?><br />
						  				<?php if($rowCount == floor($totalRows/5)  || $totalCount == $totalRows): ?>
						  						</td>
						  				<?php $rowCount = 1 ?>
						  				<?php continue; ?>
						  				<?php endif; ?>
						  				
						  				<?php $rowCount++ ?>
						  				
						  			<?php endforeach; ?>
						  				 
			  					 </tr>
			  				</tbody>
			  			</table>
			  		</td>		 
			  	</tr>
		  	</table>	
		</div>
</div>