<?php
    $HTMLFormID = $this->getHTMLFormID();
    $userOfficeVO = $this->getUserOfficeVO();
    if($userOfficeVO == null){
    	$userOfficeVO = new Margshri_WebPortal_VO_Master_Office_UserOfficeVO();
    }

    $statusOptions   = $this->getStatusOptions();
    $officeOptions   = $this->getOfficeOptions();
    
?>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">User Office</h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
										 
					<tr>
						<td class="label">
							<label for="OfficeID">Office<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="OfficeID" id="OfficeID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($officeOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($userOfficeVO->getOfficeID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
						</td>
					</tr>
					
					 
					<tr>
						<td class="label">
							<label for="StatusID">Status<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="StatusID" id="StatusID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($statusOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($userOfficeVO->getStatusID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
							<input type="hidden" id="AdminUserID" name="AdminUserID" value="<?php echo $this->getAdminUserID() ?>" />
							<input type="hidden" id="ID" name="ID" value="<?php echo ($userOfficeVO->getID() > 0) ? $userOfficeVO->getID() : 0 ?>" />
						</td>
					</tr>
					
				</tbody>
			</table>
				
		</div>
	</div>
</div>