<?php
    $HTMLFormID = $this->getHTMLFormID();
    $bidVO = $this->getBidVO();
    //$tableTypeOptions = $this->getTableTypeOptions();
    $statusOptions  = $this->getStatusOptions();
    //$getYesNoOptions  = $this->getYesNoOptions();
    $bidTypeOptions  = $this->getBidTypeOptions();
    if($bidVO == null){
    	$bidVO = new Margshri_WebPortal_VO_Master_Right_BidVO();
    }
?>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Bidding</h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
					<tr>
						<td class="label">
							<label for="BidName">Bid Name<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="BidName" id="BidName" 
							value="<?php echo $bidVO->getBidName() ?>" 
							class="required-entry input-text" />
						</td>
					</tr>
					
					
					<tr>
						<td class="label">
							<label for="BidCode">Bid Code<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="BidCode" id="BidCode" 
							value="<?php echo $bidVO->getBidCode() ?>" 
							class="required-entry input-text" />
						</td>
					</tr>
					
					<tr>
						<td class="label"><label for="BiddingDate">Bidding Date<span
								class="required">*</span>
						</label>
						</td>
						<td class="value"><input id="BiddingDate"
							name="LaunchDate" readonly="readonly"
							value="<?php echo $bidVO->getBiddingDate() ?>"
							class="required-entry input-text" type="text" /> 
							<img src="<?php  echo Mage::getDesign()->getSkinUrl('images/grid-cal.gif') ?>"
							alt="" class="v-middle" id="BiddingDateIMG"
							title="Select Date" style=""> 
							<script type="text/javascript">
		                                 //<![CDATA[ 
		                                 Calendar.setup({
		                                                  inputField: "BiddingDate",
		                                                  ifFormat: "%Y-%m-%d",
		                                                  showsTime: false,
		                                                  button: "BiddingDateIMG",
		                                                  align: "Bl",
		                                                  onClose   : function() { this.hide(); return validationControl.dateTime(); },
		                                                  singleClick : true
		                                               });
                                        //]]> 
                                    </script>
						</td>	
					</tr>
					
					
					<tr>
						<td class="label">
							<label for="BiddingTime">BiddingTime<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="BiddingTime" id="BiddingTime" 
							value="<?php echo $bidVO->getBiddingTime() ?>" 
							class="required-entry input-text" />
							<span>Ex. (hh:mm:ss) (24 hours format)</span>
						</td>
					</tr>
					 
					<!--  		
					<tr>
						<td class="label">
							<label for="CounterTime">Counter Time<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="CounterTime" id="CounterTime"  
							value="<?php // echo $bidVO->getCounterTime() ?>" 
							class="required-entry input-text validate-digits" />
							<span>in second</span>
						</td>
					</tr>
					-->
					
					<tr>
						<td class="label">
							<label for="TypeID">Bid Type<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="TypeID" id="TypeID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($bidTypeOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($bidVO->getTypeID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
						</td>
					</tr>
					
					
					<tr>
						<td class="label">
							<label for="StatusID">Status<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="StatusID" id="StatusID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($statusOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($bidVO->getStatusID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
							
							<input type="hidden" id="ID" name="ID" value="<?php echo ($bidVO->getID() > 0) ? $bidVO->getID() : 0 ?>" />
						</td>
					</tr>
					
				</tbody>
			</table>
				
				 
				
		</div>
	</div>
</div>