<?php
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-permissions-role"><?php echo $this->__('Report') ?></h3></td>
            <td class="form-buttons">
            <?php  //if(Dakiya_Helper_Utility::isACLAllowed('admin/master/email/emailtemplate/add/')): ?>
            	<button class="scalable add" onclick="window.location='<?php echo $this->getAddNewUrl() ?>'"><span><?php echo $this->__('Add New') ?></span></button>
            <?php  //endif;?>
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getGridHtml() ?>