<?php
$programmeDataObjs = $this->getProgrammeList();
?>

<?php if(sizeof($programmeDataObjs) > 0): ?>

<div class="card bg-light text-dark" style="margin: 50px 0px 10px 0px !important;">
	<div class="card-body" style="padding:0px !important;">
		<table class="table" style="margin-bottom: 0px !important;">
			<tbody>
				<tr>
					<td style="border-top:none; width: 20% !important;" class="text-left">
						<span style="font-size:20px;" onclick="baseFormJS.redirect('<?php echo $this->getUrl('') ?>')">&laquo;</span>
					</td>
					
					<td style="border-top:none; vertical-align: middle;" class="text-center">
						<span style="font-weight:bold;">Donor List</span>
					</td>
					
					<td style="border-top:none; width: 20% !important; vertical-align: middle; " class="text-left">
						<span style="font-weight:bold;"><?php // echo $totalDonation; ?></span>	
					</td>
				</tr>
			</tbody>
		</table>
	</div>
	
	<div class="card-body" style="padding:0px !important;">
		<table class="table" style="margin-bottom: 0px !important;">
			<tbody>
				<tr>
					<td style="border-top:none; vertical-align: middle;" class="text-center">
						<input class="form-control" id="Search" type="text" placeholder="Search..">
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

<div class="card bg-light">
    <div class="card-body" id="ProgrammeContainer" style="padding: unset !important;" >
        <ul class="list-group" id="ProgrammeList">
        <?php foreach($programmeDataObjs as $programmeDataObj): ?>
        	<li class="list-group-item" onclick="return baseFormJS.redirect('<?php echo $this->getUrl("common/Frontend_Donor_Donor/showDonorList", array("ProgrammeID"=> $programmeDataObj['ProgrammeID'])) ?>')" >
            	<div class="media">
                    <div class="media-body text-left">
                        <p style="margin-bottom: 0px !important;" ><?php echo $programmeDataObj['ProgrammeName'] ?></p>
                    </div>
            	</div>
        	</li>
    	<?php endforeach; ?>
    	</ul>
    </div>
</div>

<script>
$(document).ready(function(){
  $("#Search").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#DonorList li").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>


<?php else: ?>

<div class="card bg-light text-dark" style="margin: 50px 0px 10px 0px !important;">
	<div class="card-body" >
		<p class="small text-center ">Record not found</p>
	</div>
</div>

<?php endif; ?>