<?php
$HTMLFormID = $this->getHTMLFormID();
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            
            <td style="width:50%;"><h3 class="icon-head head-permissions-role"><?php echo ($this->getID() !=null ) ? ($this->__('Edit Table') ) : $this->__('Add Table') ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getBackButtonHtml() ?>
                <?php echo $this->getResetButtonHtml() ?>
                <?php echo $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>

<form action="<?php echo $this->getUrl('*/*/save') ?>" method="post" id="<?php echo $HTMLFormID ?>">
    <?php  echo $this->getBlockHtml('formkey')?>
    <?php  echo $this->getEntropy()?>
</form>

<script type="text/javascript">

function tableVO(){
	this.ID = null;
	this.Value = null;
	this.Code = null;
	this.Discription = null;
	this.TableTypeID = null;
	this.FileName = null;
	this.IsFileName = null;
	this.UseInSearch = null;
	this.UseInCLP = null;
	this.MinCLPPoint = null;
	this.MaxCLPPoint = null;
	this.StatusID=null;
	
}
var newTableDTO = new tableVO();

var formObj = new varienForm('<?php echo $HTMLFormID; ?>');
var formJS={

		submit : function(){
    		if(!formJS.saveValidation()) return ;
				formJS.saveAjax();
		},

		saveValidation : function(){
			var errorMsg = '';
         	if(!(formObj.validator && formObj.validator.validate())){
    	    	return false;
	    	}

         	// SET VOs 
         	newTableDTO.ID = ($('ID').value).strip();
         	newTableDTO.Value = ($('Value').value).strip();
         	newTableDTO.Code = ($('Code').value).strip();
         	newTableDTO.Discription = ($('Discription').value).strip();
         	newTableDTO.TableTypeID = ($('TableTypeID').value).strip();
         	newTableDTO.FileName = ($('FileName').value).strip();
         	newTableDTO.IsFileName = ($('IsFileName').value).strip();
         	newTableDTO.UseInSearch = ($('UseInSearch').value).strip();
         	newTableDTO.UseInCLP = ($('UseInCLP').value).strip();

         	newTableDTO.MinCLPPoint = ($('MinCLPPoint').value).strip();
         	if(newTableDTO.MinCLPPoint == null || newTableDTO.MinCLPPoint == ''){
         		newTableDTO.MinCLPPoint = 0;
            }
            
         	newTableDTO.MaxCLPPoint = ($('MaxCLPPoint').value).strip();
         	if(newTableDTO.MaxCLPPoint == null || newTableDTO.MaxCLPPoint == ''){
         		newTableDTO.MaxCLPPoint = 0;
            }
         	
         	
         	newTableDTO.StatusID = ($('StatusID').value).strip(); 
         	
         	if(errorMsg != ''){
            	alert(errorMsg);
				return false;
			}

			return true;	
		},	

        saveAjax: function(){
        	var URL = "<?php echo $this->getUrl('*/*/save')?>" ;
		    var parameters= {"TableDataObj": JSON.stringify(newTableDTO,null) };
		    var callBackMethod ="formJS.responseSave";
		    var callBackArgs =null;
		    ajaxRequest.execute(	URL, parameters, callBackMethod , callBackArgs );
		    return false;
     	},

	    responseSave : function(response,args) {
        	if(response.SuccessMessage !=null){
			 	window.location.href = "<?php echo $this->getUrl('*/*/index')?>";
			 	return;
			}else if(response.ErrorMessage !=null){
				alert(response.ErrorMessage);
    			return false;
 			}
 	 	}
		
		 
			
}; 

</script>