<?php
    $HTMLFormID = $this->getHTMLFormID();
    $officeTypeVO = $this->getOfficeTypeVO();
    $statusOptions  = $this->getStatusOptions();
    
    if($officeTypeVO == null){
    	$officeTypeVO = new Margshri_WebPortal_VO_Master_Office_OfficeTypeVO();
    }
?>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Office Type</h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
					<tr>
						<td class="label">
							<label for="Value">Office Type Name<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="Value" id="Value" 
							value="<?php echo $officeTypeVO->getValue() ?>" 
							class="required-entry input-text" />
						</td>
					</tr>
					
					<tr>
						<td class="label">
							<label for="Code">Office Type Code<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="Code" id="Code" 
							value="<?php echo $officeTypeVO->getCode() ?>" 
							class="required-entry input-text" />
						</td>
					</tr>
										
					<tr>
						<td class="label">
							<label for="StatusID">Status<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="StatusID" id="StatusID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($statusOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($officeTypeVO->getStatusID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
							
							<input type="hidden" id="ID" name="ID" value="<?php echo ($officeTypeVO->getID() > 0) ? $officeTypeVO->getID() : 0 ?>" />
						</td>
					</tr>
					
					
				</tbody>
			</table>
		</div>
	</div>
</div>