<?php
$HTMLFormID = $this->getHTMLFormID();
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            
            <td style="width:50%;"><h3 class="icon-head head-permissions-role"><?php echo ($this->getID() != null ) ? ($this->__('Edit') ) : $this->__('Add') ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getBackButtonHtml() ?>
                <?php echo $this->getResetButtonHtml() ?>
                <?php echo $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>

<form action="<?php echo $this->getUrl('*/*/save') ?>" method="post" id="<?php echo $HTMLFormID ?>">
    <?php  echo $this->getBlockHtml('formkey')?>
    <?php  echo $this->getEntropy()?>
</form>

<script type="text/javascript">

function RecruitmentVO(){
	this.ID = null;
	this.Value = null;
	this.Code = null;

	this.Department = null;
	this.PostName = null;
	this.NoOfPost = null;
	this.Qualification = null;
	this.OpeningDate = null;
	this.LastDate = null;
	this.ExamDate = null;
	this.ApplyOnlineLink = null;
	this.MoreDetailLink = null;
		
	this.RecruitmentTypeID = null;
	this.AgeLimit = null;
	this.Fees = null;
	
	this.StatusID=null;
	this.PinCode=null;
	this.Address = null;
	this.CountryID = null;
	this.StateID = null;
	this.DistrictID=null;
	this.CityID=null;
	
}
var newRecruitmentDTO = new RecruitmentVO();

var formObj = new varienForm('<?php echo $HTMLFormID; ?>');
var formJS={

		submit : function(){
    		if(!formJS.saveValidation()) return ;
				formJS.saveAjax();
		},

		saveValidation : function(){
			var errorMsg = '';

         	if(!(formObj.validator && formObj.validator.validate())){
    	    	return false;
	    	}
         	
         	// SET VOs 
         	newRecruitmentDTO.ID = ($('ID').value).strip();
         	newRecruitmentDTO.Value = ($('Value').value).strip();
         	newRecruitmentDTO.Code = ($('Code').value).strip();
         	newRecruitmentDTO.RecruitmentTypeID = ($('RecruitmentTypeID').value).strip();
         	newRecruitmentDTO.Department = ($('Department').value).strip();
         	newRecruitmentDTO.PostName = ($('PostName').value).strip();
         	newRecruitmentDTO.NoOfPost = ($('NoOfPost').value).strip();
         	newRecruitmentDTO.Qualification = ($('Qualification').value).strip();
         	newRecruitmentDTO.OpeningDate = ($('OpeningDate').value).strip();
         	newRecruitmentDTO.LastDate = ($('LastDate').value).strip();
         	newRecruitmentDTO.ExamDate = ($('ExamDate').value).strip();
         	newRecruitmentDTO.ApplyOnlineLink = ($('ApplyOnlineLink').value).strip();
         	newRecruitmentDTO.MoreDetailLink = ($('MoreDetailLink').value).strip();
         	newRecruitmentDTO.StatusID = ($('StatusID').value).strip();
         	newRecruitmentDTO.PinCode = ($('PinCode').value).strip();
         	newRecruitmentDTO.Address = ($('Address').value).strip();
         	newRecruitmentDTO.CountryID = ($('CountryID').value).strip();
         	newRecruitmentDTO.StateID = ($('StateID').value).strip();
         	newRecruitmentDTO.DistrictID = ($('DistrictID').value).strip();
         	newRecruitmentDTO.CityID = ($('CityID').value).strip();

         	newRecruitmentDTO.AgeLimit = ($('AgeLimit').value).strip();
         	newRecruitmentDTO.Fees = ($('Fees').value).strip();
         	
         	if(errorMsg != ''){
            	alert(errorMsg);
				return false;
			}

			return true;	
		},	

        saveAjax: function(){
        	var URL = "<?php echo $this->getUrl('*/*/save')?>" ;
		    var parameters= {"RecruitmentDataObj": JSON.stringify(newRecruitmentDTO,null) };
		    var callBackMethod ="formJS.responseSave";
		    var callBackArgs =null;
		    ajaxRequest.execute(	URL, parameters, callBackMethod , callBackArgs );
		    return false;
     	},

	    responseSave : function(response,args) {
        	if(response.SuccessMessage !=null){
			 	window.location.href = "<?php echo $this->getUrl('*/*/index')?>" ;
			 	return;
			}else if(response.ErrorMessage !=null){
				alert(response.ErrorMessage);
    			return false;
 			}
 	 	},
		
		setDistrictList: function(stateID){
			//var stateID = obj.value;
			var innerHTML = '<option value="">--Select--</option>';
			for(var key in districtList){
				if(districtList[key].StateID == stateID){
					if(key == RECRUITMENTVO.DistrictID)
						innerHTML += '<option value="'+key+'" selected = "selected">'+districtList[key].Name+'</option>';
					else
						innerHTML += '<option value="'+key+'">'+districtList[key].Name+'</option>';	
				}
			}
			UI.elementDisabled($('DistrictID'), false);
			$('DistrictID').innerHTML = innerHTML;
			return; 
		},

		setCityList: function(districtID){
			//var districtID = obj.value;
			var innerHTML = '<option value="">--Select--</option>';
			for(var key in cityList){
				if(cityList[key].DistrictID == districtID){
					if(key == RECRUITMENTVO.CityID)
						innerHTML += '<option value="'+key+'" selected = "selected">'+cityList[key].Name+'</option>';
					else		
						innerHTML += '<option value="'+key+'">'+cityList[key].Name+'</option>';
				}
			}
			UI.elementDisabled($('CityID'), false);
			$('CityID').innerHTML = innerHTML;
			return; 
		},

		setCategoryBox: function(obj){
			var categoryID   = obj.value;
			var categoryName = obj.name;
			var categoryValueID; 

			switch(categoryName){
				case 'Category1ID':
					categoryValueID = 'Category1Value';	
					break;
				case 'Category2ID':
					categoryValueID = 'Category2Value';
					break;
				case 'Category3ID':
					categoryValueID = 'Category3Value';
					break;		 
			}
			
			if(categoryID != ''){
				UI.elementVisibility($(categoryValueID),"block");
			}else{
				UI.elementVisibility($(categoryValueID),"none");
				$(categoryValueID).value = '';
			}			
			return false;			 
		},
		

		defaultSetting: function(){
			UI.elementDisabled($('DistrictID'), true);
			UI.elementDisabled($('CityID'), true);

			UI.elementVisibility($("Category1Value"),"none");
			UI.elementVisibility($("Category2Value"),"none");
			UI.elementVisibility($("Category3Value"),"none");
		}
			
}; 


// FOR EDIT 
if(RECRUITMENTVO != ''){
	formJS.setDistrictList(RECRUITMENTVO.StateID);
	formJS.setCityList(RECRUITMENTVO.DistrictID);		
	
}else{
	formJS.defaultSetting();
}

</script>