<?php
$HTMLFormID = $this->getHTMLFormID();
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            
            <td style="width:50%;"><h3 class="icon-head head-permissions-role"><?php echo ($this->getFirmID() != null ) ? ($this->__('Edit Firm') ) : $this->__('Add Firm') ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getBackButtonHtml() ?>
                <?php echo $this->getResetButtonHtml() ?>
                <?php echo $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>

<form action="<?php echo $this->getUrl('*/*/save') ?>" method="post" id="<?php echo $HTMLFormID ?>">
    <?php  echo $this->getBlockHtml('formkey')?>
    <?php  echo $this->getEntropy()?>
</form>

<script type="text/javascript">
var IS_FORM_SUBMIT=0;
function firmVO(){
	this.ID = null;
	this.Value = null;
	
    this.SortName = null;
	this.ContactPersonName = null;
	
    this.Code = null;
	this.UserID = null;
	this.Order = null;
	this.WebsiteLink = null;
	this.IsPaid = null;
	this.TinNumber = null;
	this.PANNumber = null;
	this.Category1ID = null;
	this.Category1Value = null;
	this.Category2ID = null;
	this.Category2Value = null;
	this.Category3ID = null;
	this.Category3Value = null;
	this.TableCodes = null;
	this.SubPageTableCode = null;
	this.SubPageURL = null;

	this.UseInCLP = null;
	this.MinCLPPoint = null;
	this.MaxCLPPoint = null;
	
	this.StatusID=null;
	this.LandLineNumber=null;
	this.MobileNumber1=null;
	this.MobileNumber2=null;

    this.CustomerCareNumber=null;
    this.EmergencyNumber=null;
    this.TollFree=null;

	this.Email=null;
	this.PinCode=null;
	this.Address = null;
	this.CountryID = null;
	this.StateID = null;
	this.DistrictID=null;
	this.CityID=null;
	this.Area=null;

	//this.TableName=null;
	
	this.BusinessDay=null;
	this.BusinessHours=null;
	this.ACRegistrationNo = null;
	this.RtelNumber = null;
	this.KumLicenceNo = null;
	this.IsOnlineShopping=null;
	this.PriorityID=null;
	 
	
	this.UniqueID = null;
	this.Password=null;
	this.PaymentMethodID=null;
	this.PaymentMethod = null;
	
	
	this.TableVOs=null;
}
var newFirmDTO = new firmVO();

function tableVO(){
	this.Code = null;
}


var formObj = new varienForm('<?php echo $HTMLFormID; ?>');
var formJS={

		submit : function(){
    		if(!formJS.saveValidation()) return ;
				formJS.saveAjax();
		},

		saveValidation : function(){
			var errorMsg = '';
			
         	if(!(formObj.validator && formObj.validator.validate())){
    	    	return false;
	    	}
         	
         	// SET VOs 
         	newFirmDTO.ID = ($('ID').value).strip();
         	newFirmDTO.Value = ($('Value').value).strip();

			newFirmDTO.SortName = ($('SortName').value).strip();
			newFirmDTO.ContactPersonName = ($('ContactPersonName').value).strip();

         	newFirmDTO.Code = null;
         	newFirmDTO.UserID = null;
         	newFirmDTO.Order = null;
         	newFirmDTO.WebsiteLink = ($('WebsiteLink').value).strip();
         	if($("IsPaid").checked == true){
         		newFirmDTO.IsPaid = 1;
			}else{
				newFirmDTO.IsPaid = 0;
			}
         	newFirmDTO.TinNumber = ($('TinNumber').value).strip();
         	newFirmDTO.PANNumber = ($('PANNumber').value).strip();
         	newFirmDTO.Category1ID = ($('Category1ID').value).strip();
         	newFirmDTO.Category1Value = ($('Category1Value').value).strip();
         	newFirmDTO.Category2ID = ($('Category2ID').value).strip();
         	newFirmDTO.Category2Value = ($('Category2Value').value).strip();
         	newFirmDTO.Category3ID = ($('Category3ID').value).strip();
         	newFirmDTO.Category3Value = ($('Category3Value').value).strip();
         	newFirmDTO.SubPageTableCode = ($('SubPageTableCode').value).strip();
         	newFirmDTO.SubPageURL = ($('SubPageURL').value).strip();

         	if($("UseInCLP").checked == true){
         		newFirmDTO.UseInCLP = 1;
			}else{
				newFirmDTO.UseInCLP = 0;
			}
			
         	newFirmDTO.MinCLPPoint = ($('MinCLPPoint').value).strip();
         	newFirmDTO.MaxCLPPoint = ($('MaxCLPPoint').value).strip();
        	

         	newFirmDTO.StatusID = ($('StatusID').value).strip();
         	newFirmDTO.LandLineNumber = ($('LandLineNumber').value).strip();
         	newFirmDTO.MobileNumber1 = ($('MobileNumber1').value).strip();
         	newFirmDTO.MobileNumber2 = ($('MobileNumber2').value).strip();

			newFirmDTO.CustomerCareNumber = ($('CustomerCareNumber').value).strip();
			newFirmDTO.EmergencyNumber = ($('EmergencyNumber').value).strip();
			newFirmDTO.TollFree = ($('TollFree').value).strip();
         	
			newFirmDTO.Email = ($('Email').value).strip();
         	newFirmDTO.PinCode = ($('PinCode').value).strip();
         	newFirmDTO.Address = ($('Address').value).strip();
         	newFirmDTO.CountryID = ($('CountryID').value).strip();
         	newFirmDTO.StateID = ($('StateID').value).strip();
         	newFirmDTO.DistrictID = ($('DistrictID').value).strip();
         	newFirmDTO.CityID = ($('CityID').value).strip();
			newFirmDTO.Area = ($('Area').value).strip();
         	//newFirmDTO.TableName = ($('TableName').value).strip();
         	
         	
         	//newFirmDTO.BusinessDay = ($('BusinessDay').value).strip();
         	newFirmDTO.BusinessHours = ($('BusinessHours').value).strip();
         	newFirmDTO.ACRegistrationNo = ($('ACRegistrationNo').value).strip();
         	newFirmDTO.RtelNumber = ($('RtelNumber').value).strip();
         	newFirmDTO.KumLicenceNo = ($('KumLicenceNo').value).strip();
         	newFirmDTO.PriorityID = ($('PriorityID').value).strip();
         	newFirmDTO.UniqueID = ($('UniqueID').value).strip();
         	newFirmDTO.Password = ($('Password').value).strip();
         	//newFirmDTO.PaymentMethodID = ($('PaymentMethodID').value).strip();
			

			// SET BUSINESS DAYS
			var businessDayContainer = $('BusinessDayContainer');
			var businessDayCheckedArray = new Array(); 
			var checkedRowIndex = 0;
			for(rowIndex=0; rowIndex<businessDayContainer.rows.length; rowIndex++){
				if(businessDayContainer.rows[rowIndex].children[0].children[0].checked){
					var value = businessDayContainer.rows[rowIndex].children[0].children[0].value;
					businessDayCheckedArray[checkedRowIndex]=value;
					checkedRowIndex++;		 			
				}
			}

			var businessDayString = '';
			for(checkedRowIndex=0; checkedRowIndex<businessDayCheckedArray.length; checkedRowIndex++){
				if(checkedRowIndex == 0 && businessDayCheckedArray.length == 1){
					businessDayString = businessDayCheckedArray[checkedRowIndex];
				}else if(checkedRowIndex == (businessDayCheckedArray.length-1)){
					businessDayString += businessDayCheckedArray[checkedRowIndex];
				}else{
					businessDayString += businessDayCheckedArray[checkedRowIndex] + "|";
				}				
			}
			newFirmDTO.BusinessDay = businessDayString;



			// SET PAYMENT METHODS
			var paymentMethodContainer = $('PaymentMethodContainer');
			var paymentMethodCheckedArray = new Array(); 
			var checkedRowIndex = 0;
			for(rowIndex=0; rowIndex<paymentMethodContainer.rows.length; rowIndex++){
				if(paymentMethodContainer.rows[rowIndex].children[0].children[0].checked){
					var value = paymentMethodContainer.rows[rowIndex].children[0].children[0].value;
					paymentMethodCheckedArray[checkedRowIndex]=value;
					checkedRowIndex++;		 			
				}
			}

			var paymentMethodString = '';
			for(checkedRowIndex=0; checkedRowIndex<paymentMethodCheckedArray.length; checkedRowIndex++){
				if(checkedRowIndex == 0 && paymentMethodCheckedArray.length == 1){
					paymentMethodString = paymentMethodCheckedArray[checkedRowIndex];
				}else if(checkedRowIndex == (paymentMethodCheckedArray.length-1)){
					paymentMethodString += paymentMethodCheckedArray[checkedRowIndex];
				}else{
					paymentMethodString += paymentMethodCheckedArray[checkedRowIndex] + "|";
				}				
			}
			newFirmDTO.PaymentMethod = paymentMethodString;
			

         	if($("IsOnlineShopping").checked == true){
         		newFirmDTO.IsOnlineShopping = 1;
			}else{
				newFirmDTO.IsOnlineShopping = 0;
			}
         	
         	if($('Category1Value').style.display != 'none'){
             	if(newFirmDTO.Category1Value == '' || newFirmDTO.Category1Value == null)
         			errorMsg += "Please Enter First Category Value \n"; 
            }else{
            	newFirmDTO.Category1ID = null;
            }

         	if($('Category2Value').style.display != 'none'){
             	 if(newFirmDTO.Category2Value == '' || newFirmDTO.Category2Value == null)
         		errorMsg += "Please Enter Second Category Value \n"; 
            }else{
            	newFirmDTO.Category2ID = null;
            }

            if($('Category3Value').style.display != 'none'){
              	 if(newFirmDTO.Category3Value == '' || newFirmDTO.Category3Value == null)
	           		errorMsg += "Please Enter Third Category Value \n"; 
            }else{
               	newFirmDTO.Category3ID = null;
            }


            if(newFirmDTO.MobileNumber1 != null && newFirmDTO.MobileNumber1 != '' && 
                    newFirmDTO.MobileNumber2 != null && newFirmDTO.MobileNumber2 != ''){
				if(newFirmDTO.MobileNumber1 == newFirmDTO.MobileNumber2){
					$('MobileNumber2').value = "";
					$('MobileNumber2').focus();
					errorMsg += "Both Mobile Number Can`t Be Same ! \n";
				}
            }

            if(newFirmDTO.WebsiteLink != null && newFirmDTO.WebsiteLink != ''){
				var re = new RegExp("^http(s?)\:\/\/[0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*(:(0-9)*)*(\/?)([a-zA-Z0-9\-\.\?\,\'\/\\\+&amp;%\$#_]*)?$");
	         	if (!re.test(newFirmDTO.WebsiteLink)) { 
	         		errorMsg = "Invalid Website Link ! \n";
	         	}
            } 	

			var atLeastOneTableChecked = false;
			if(tableList != ''){
				var newTableDTOs = new Object();
				for(var tableCode in tableList){
					if($(tableCode).checked){
						atLeastOneTableChecked = true;
						var newTableDTO = new tableVO();
						newTableDTO.Code = tableCode;
						newTableDTOs[newTableDTO.Code] = newTableDTO;  
					}
				}
				newFirmDTO.TableVOs = newTableDTOs
			}
            
			if(atLeastOneTableChecked == false){
				errorMsg = "Please Select Atleast One Table ! \n";
			}	
         	
         	if(errorMsg != ''){
            	alert(errorMsg);
				return false;
			}

         	
			if(IS_FORM_SUBMIT == 0){
				IS_FORM_SUBMIT = 1;
				return true;
			}else{
				return false;
			}
				
		},	

        saveAjax: function(){
        	var URL = "<?php echo $this->getUrl('*/*/save')?>" ;
		    var parameters= {"FirmDataObj": JSON.stringify(newFirmDTO,null) };
		    var callBackMethod ="formJS.responseSave";
		    var callBackArgs =null;
		    ajaxRequest.execute(	URL, parameters, callBackMethod , callBackArgs );
		    return false;
     	},

	    responseSave : function(response,args) {
	    	//IS_FORM_SUBMIT=0;
	    	if(response.SuccessMessage !=null){
	    		window.location.href = "<?php echo $this->getUrl('*/*/index')?>";
			 	return;
			}else if(response.ErrorMessage !=null){
				alert(response.ErrorMessage);
				return false;
 			}
 	 	},
		
		setDistrictList: function(stateID){
			//var stateID = obj.value;
			var innerHTML = '<option value="">--Select--</option>';
			for(var key in districtList){
				if(districtList[key].StateID == stateID){
					if(key == FIRMVO.DistrictID)
						innerHTML += '<option value="'+key+'" selected = "selected">'+districtList[key].Name+'</option>';
					else
						innerHTML += '<option value="'+key+'">'+districtList[key].Name+'</option>';	
				}
			}
			UI.elementDisabled($('DistrictID'), false);
			$('DistrictID').innerHTML = innerHTML;
			return; 
		},

		setCityList: function(districtID){
			//var districtID = obj.value;
			var innerHTML = '<option value="">--Select--</option>';
			for(var key in cityList){
				if(cityList[key].DistrictID == districtID){
					if(key == FIRMVO.CityID)
						innerHTML += '<option value="'+key+'" selected = "selected">'+cityList[key].Name+'</option>';
					else		
						innerHTML += '<option value="'+key+'">'+cityList[key].Name+'</option>';
				}
			}
			UI.elementDisabled($('CityID'), false);
			$('CityID').innerHTML = innerHTML;
			return; 
		},

		setCategoryBox: function(obj){
			var categoryID   = obj.value;
			var categoryName = obj.name;
			var categoryValueID; 

			switch(categoryName){
				case 'Category1ID':
					categoryValueID = 'Category1Value';	
					break;
				case 'Category2ID':
					categoryValueID = 'Category2Value';
					break;
				case 'Category3ID':
					categoryValueID = 'Category3Value';
					break;		 
			}
			
			if(categoryID != ''){
				UI.elementVisibility($(categoryValueID),"block");
			}else{
				UI.elementVisibility($(categoryValueID),"none");
				$(categoryValueID).value = '';
			}			
			return false;			 
		},
		

		defaultSetting: function(){
			UI.elementDisabled($('DistrictID'), true);
			UI.elementDisabled($('CityID'), true);

			UI.elementVisibility($("Category1Value"),"none");
			UI.elementVisibility($("Category2Value"),"none");
			UI.elementVisibility($("Category3Value"),"none");
		}
			
}; 


// FOR EDIT 
if(FIRMVO != ''){

	if(FIRMVO.Category1Value != '' && FIRMVO.Category1Value != null){
		UI.elementVisibility($("Category1Value"),"block");
	}else{
		UI.elementVisibility($("Category1Value"),"none");
	}

	if(FIRMVO.Category2Value != '' && FIRMVO.Category2Value != null ){
		UI.elementVisibility($("Category2Value"),"block");
	}else{
		UI.elementVisibility($("Category2Value"),"none");
	}

	if(FIRMVO.Category3Value != '' && FIRMVO.Category3Value != null){
		UI.elementVisibility($("Category3Value"),"block");
	}else{
		UI.elementVisibility($("Category3Value"),"none");
	}

	
	formJS.setDistrictList(FIRMVO.StateID);
	formJS.setCityList(FIRMVO.DistrictID);		
	
}else{
	formJS.defaultSetting();
}

</script>
