<?php
$title      = Mage::helper('webportal/Data')->getPageTitleByTableCode($this->getTableCode());
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-permissions-role"><?php echo $this->__($title) ?></h3></td>
            <td class="form-buttons">
            <button class="scalable add" onclick="window.location='<?php echo $this->getAddNewUrl() ?>'"><span><?php echo $this->__('Add New') ?></span></button>
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getGridHtml() ?>
