<?php
    $HTMLFormID = $this->getHTMLFormID();
    $entityAttributeVO = $this->getEntityAttributeVO();
    $entityOptions  = $this->getEntityOptions();
    $attributeOptions  = $this->getAttributeOptions();
    $statusOptions  = $this->getStatusOptions();
    
    if($entityAttributeVO == null){
    	$entityAttributeVO = new Margshri_WebPortal_VO_Master_SubPage_EntityAttributeVO();
    }
?>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Sub Page Entity Attribute</h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
					
					<tr>
						<td class="label">
							<label for="EntityID">Entity<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="EntityID" id="EntityID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($entityOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($entityAttributeVO->getEntityID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td class="label">
							<label for="AttributeID">Attribute<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="AttributeID" id="AttributeID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($attributeOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($entityAttributeVO->getAttributeID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td class="label">
							<label for="StatusID">Status<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="StatusID" id="StatusID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($statusOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($entityAttributeVO->getStatusID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
							
							<input type="hidden" id="ID" name="ID" value="<?php echo ($entityAttributeVO->getID() > 0) ? $entityAttributeVO->getID() : 0 ?>" />
						</td>
					</tr>
					
				</tbody>
			</table>
				
				 
		</div>
	</div>
</div>