<?php
    $_htmlId  = $this->getHtmlId(); 
?>
        <div class="entry-edit">
            <div class="entry-edit-head">
 					<h4 class="icon-head head-edit-form fieldset-legend">Price Upload</h4>
                <div class="form-buttons"></div>
            </div>
   
            <div class="fieldset " id="base_fieldset">
                <div class="hor-scroll">
                 
                    <table cellspacing="0" class="form-list">
                            <tbody>
                                <tr>
                                        <td class="label">
                                                <label for="file">Upload File (Type xls, xlsx)<span class="required">*</span></label>
                                        </td>
                                        <td class="value">
                                        			<input type="file" name="file" id="file" value="<?php //echo $this->getInfoData('TypeCode') ?>" title="Type Code" class=" required-entry input-text" style="width: 110px ! important;text-align:left"  /> 
										 </td>
                                  </tr>
                            </tbody>  
                    </table>
                 
                </div>
            </div>

    </div>
 