<?php ?>
<style>
<!--
.fixed_footer{
   position: fixed;
   left: 0;
   bottom: 0;
   width: 100%;
   /* text-align: center; */
}
-->
</style>
<div class="fixed_footer bg-white border">
  <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . "frontend/default/margshri/images/home.jpg" ?>" alt="donor list" class="mr-3 mt-3 rounded-circle text-left" style="width:50px; margin: 5px !important;" onclick="return baseFormJS.redirect('<?php echo $this->getUrl("") ?>')" />
</div>
