<?php ?>


<div class="row text-center">
  <!--  	
  <div class="col" onclick="return baseFormJS.redirect('<?php // echo $this->getUrl("common/Frontend_Donor_Donor/showGoCoronaDonorList") ?>')" >
      <div>
      	<img src="<?php // echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . "frontend/default/margshri/images/photos.png" ?>" alt="photos" style="width:50px !important;" />
      </div>
      <div>
      	<p class="small text-monospace font-weight-light">Photos</p>
      </div>
  </div>
  
  <div class="col" onclick="return baseFormJS.redirect('<?php // echo $this->getUrl("common/Frontend_Donor_Donor/showGoCoronaDonorList") ?>')" >
      <div>
      	<img src="<?php // echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . "frontend/default/margshri/images/photos.png" ?>" alt="photos" style="width:50px !important;" />
      </div>
      <div>
      	<p class="small text-monospace font-weight-light">Videos</p>
      </div>
  </div>
  -->
  
  <div class="col" onclick="return baseFormJS.redirect('<?php echo $this->getUrl("common/Frontend_Member_Member/showExecutiveMemberList") ?>')" >
      <div>
      	<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . "frontend/default/margshri/images/team.png" ?>" alt="photos" style="width:50px !important;" />
      </div>
      <div>
      	<p class="small text-monospace font-weight-light">Team</p>
      </div>
  </div>
  
  <div class="col" onclick="return baseFormJS.redirect('<?php echo $this->getUrl("common/Frontend_Programme_Programme/showProgrammeList", array("Code"=>"donation")) ?>')" >
  	  <div>
      	<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . "frontend/default/margshri/images/donation.png" ?>" alt="donation" style="width:50px !important;" />
      </div>
      <div>
      	<p class="small text-monospace font-weight-light">Donation</p>
      </div>
  </div>
  
  
  <div class="col" onclick="return baseFormJS.redirect('<?php echo $this->getUrl("common/Frontend_Donor_Donor/showBloodDonorFilterForm", array("Code"=>"bloodDonor")) ?>')" >
  	  <div>
      	<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . "frontend/default/margshri/images/bloodDonor.png" ?>" alt="bloodDonation" style="width:50px !important;" />
      </div>
      <div>
      	<p class="small text-monospace font-weight-light">Blood Donor</p>
      </div>
  </div>
  	
  
  <div class="col" onclick="return baseFormJS.redirect('<?php echo $this->getUrl("medicalcamp/Registration_Registration/index", array("Code"=>"registerOnline")) ?>')" >
  	  <div>
      	<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . "frontend/default/margshri/images/registerOnline.png" ?>" alt="registerOnline" style="width:50px !important;" />
      </div>
      <div>
      	<p class="small text-monospace font-weight-light">Registration</p>
      </div>
  </div>
  	
  	
</div>


<!--  
<div class="card bg-light text-dark" style="margin-top: 10px !important;">
	<div class="card-body" style="padding:0px !important;">
		<div id="TopMenuDiv" class="carousel slide" data-ride="carousel" data-interval="false">
      -->  
        	<!-- The slideshow -->
        	<!--  
        	<div class="carousel-inner">
        		<div class="carousel-item active">
        			<img src="<?php // echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . "frontend/default/margshri/images/donation.jpg" ?>" alt="donor list" class="mr-3 mt-3 mb-3 rounded-circle text-left" style="width:50px; margin: 5px !important;" onclick="return baseFormJS.redirect('<?php echo $this->getUrl("common/Frontend_Donor_Donor/showPratibhaSammanDonorList") ?>')" />
        			<h6 class="ml-2 text-left"><small>Donor</small></h6>
        		</div>
        	</div>
        	-->
        	
        	<!--  	
        	<div class="carousel-inner">
        	-->
        		<!--  
        		<div class="carousel-item active text-center">
        			<img src="<?php // echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . "frontend/default/margshri/images/contribute.png" ?>" alt="donor list" class="mr-3 mt-3 mb-3 rounded-circle text-left" style="width:50px; margin: 5px !important;" onclick="return baseFormJS.redirect('<?php echo $this->getUrl("common/Frontend_Donor_Donor/showBuddhPurnimaDonorList") ?>')" />
        			<h6 class="ml-2"><small>Buddh Purnima</small></h6>
        		</div>
        		-->
        		
        		<!--  
        		<div class="carousel-item active text-center">
        			<img src="<?php // echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . "frontend/default/margshri/images/help.png" ?>" alt="donor list" class="mr-3 mt-3 mb-3 rounded-circle text-left" style="width:50px; margin: 5px !important;" onclick="return baseFormJS.redirect('<?php echo $this->getUrl("common/Frontend_Donor_Donor/showDevrajHealthDonorList") ?>')" />
        			<h6 class="ml-2"><small>Help</small></h6>
        		</div>
        		-->
        		
        		<!--  
        		<div class="carousel-item active text-center">
        			<img src="<?php // echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . "frontend/default/margshri/images/emitra.png" ?>" alt="emitra" class="mr-3 mt-3 mb-3 rounded-circle text-left" style="width:50px; margin: 5px !important;" onclick="return baseFormJS.redirect('<?php // echo $this->getUrl("common/Frontend_Emitra_Emitra/showEmitraServiceList") ?>')" />
        			<h6 class="ml-2"><small>E-Mitra</small></h6>
        		</div>
        		-->
        		
        		<!--  
        		<div class="carousel-item active text-center">
        			<img src="<?php // echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . "frontend/default/margshri/images/member.png" ?>" alt="executive member list" class="mr-3 mt-3 mb-3 rounded-circle text-left" style="width:50px; margin: 5px !important;" onclick="return baseFormJS.redirect('<?php echo $this->getUrl("common/Frontend_Member_Member/showExecutiveMemberList") ?>')" />
        			<h6 class="ml-2"><small>Executive Member List</small></h6>
        		</div>
        		-->
        		
        		
        		<!--  
        		<div class="carousel-item active text-center">
        			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . "frontend/default/margshri/images/help.png" ?>" alt="executive member list" class="mr-3 mt-3 mb-3 rounded-circle text-left" style="width:50px; margin: 5px !important;" onclick="return baseFormJS.redirect('<?php echo $this->getUrl("common/Frontend_Donor_Donor/showGoCoronaDonorList") ?>')" />
        			<h6 class="ml-2"><small>Donor List</small></h6>
        		</div>
        	</div>
        	-->
        	
        	
        
        	<!-- Left and right controls -->
        	<!--  
        	<a class="carousel-control-prev" href="#TopMenuDiv" data-slide="prev"> 
        		<span class="carousel-control-prev-icon"></span>
        	</a> 
        	<a class="carousel-control-next" href="#TopMenuDiv" data-slide="next"> 
        		<span class="carousel-control-next-icon"></span>
        	</a>
        	-->
        	
        	
        <!--  	
        </div>
			
	</div>
</div>
-->