<?php ?>
<div class="card bg-light text-dark">
	<div class="card-body bg-light text-dark" style="padding:0px !important;">
		<div id="TopSliderDiv" class="carousel slide" data-ride="carousel">

        	<!-- Indicators -->
        	<ul class="carousel-indicators">
        		<li data-target="#TopSliderDiv" data-slide-to="0" class="active"></li>
        		<li data-target="#TopSliderDiv" data-slide-to="1"></li>
        		<li data-target="#TopSliderDiv" data-slide-to="2"></li>
        		<li data-target="#TopSliderDiv" data-slide-to="3"></li>
        		<li data-target="#TopSliderDiv" data-slide-to="4"></li>
        	</ul>
        
        	<!-- The slideshow -->
        	<div class="carousel-inner">
        		<div class="carousel-item active">
        			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "mgsr/common/images/headerslider/01.png" ?>" alt="Los Angeles" />
        			<!--  
        			<div class="carousel-caption">
                       <h3>Los Angeles</h3>
                       <p>We had such a great time in LA!</p>
                    </div>
                    -->
        		</div>
        		<div class="carousel-item">
        			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "mgsr/common/images/headerslider/02.png" ?>" alt="Chicago" />
        		</div>
        		<div class="carousel-item">
        			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "mgsr/common/images/headerslider/03.png" ?>" alt="New York" />
        		</div>
        		<div class="carousel-item">
        			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "mgsr/common/images/headerslider/04.png" ?>" alt="New York" />
        		</div>
        		<div class="carousel-item">
        			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "mgsr/common/images/headerslider/05.png" ?>" alt="New York" />
        		</div>
        	</div>
        
        	<!-- Left and right controls -->
        	<a class="carousel-control-prev" href="#TopSliderDiv" data-slide="prev">
        		<span class="carousel-control-prev-icon"></span>
        	</a>
        	
        	<a class="carousel-control-next" href="#TopSliderDiv" data-slide="next">
        		<span class="carousel-control-next-icon"></span>
        	</a>
        </div>
			
	</div>
</div>

<style>
    /* Make the image fully responsive */
    .carousel-inner img {
      width: 100%;
      height: 100%;
    }
</style>