<?php
	
    $HTMLFormID = $this->getHTMLFormID();
    $professionalVO    = $this->getProfessionalVO();    
    
    if($professionalVO == null){
    	$professionalVO = new Margshri_WebPortal_VO_Center_Content_Type2_Professional_ProfessionalVO();
    }
    
    $statusOptions  = $this->getStatusOptions();
    $professionOptions  = $this->getProfessionOptions();
    
    
?>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__("Professional") ?></h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
	   		<table class="form-list">
				<tbody>

				
					<tr>
						<td class="label">
							<label for="CustomerName">Customer Name</label>
						</td>
						<td class="label">
							<label for="CustomerName"><?php echo $professionalVO->getFirstName() . " " . $professionalVO->getLastName() ?></label>
						</td>
					</tr>
				
				
					<tr>
						<td class="label">
							<label for="ProfessionID">Profession<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="ProfessionID" id="ProfessionID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($professionOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($professionalVO->getProfessionID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td class="label">
							<label for="IsPaid">Is Paid (Profile)</label>
						</td>
						<td class="value">
							<input type="checkbox" name="IsPaid" id="IsPaid" <?php echo ($professionalVO->getIsPaid() == 1) ? "checked = 'checked'" : '' ?>>
						</td>
					</tr>
					
					
					<tr>
						<td class="label">
							<label for="StatusID">Status<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="StatusID" id="StatusID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($statusOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($professionalVO->getStatusID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
							<input type="hidden" id="CustomerID" name="CustomerID" value="<?php echo $professionalVO->getCustomerID() ?>">
							<input type="hidden" id="ID" name="ID" value="<?php echo ($professionalVO->getID() != null) ? $professionalVO->getID() : 0  ?>">
						</td>
					</tr>
					
					
				</tbody>
			</table>  		
		</div>
	</div>
</div>