<?php
	
    $HTMLFormID = $this->getHTMLFormID();
    $title      = Mage::helper('webportal/Data')->getPageTitleByTableCode($this->getTableCode());
    $type11VO    = $this->getType11VO();    
    
    if($type11VO == null){
    	$type11VO = new Margshri_WebPortal_VO_Center_Content_Type11_Type11VO($this->getTableCode());
    }
    
    $statusOptions  = $this->getStatusOptions();
    $redirectURL    = '*/*/'. $this->getTableCode();
    
?>

<script type="text/javascript">
<!--
	var REDIRECTURL = '<?php echo $this->getUrl($redirectURL) ?>';
//-->
</script>


<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $title ?></h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
		  
  			<table class="form-list">
				<tbody>
					<tr>
						<td class="label">
							<label for="Value">Name<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="Value" id="Value" 
							value="<?php echo $type11VO->getValue() ?>" 
							class="required-entry input-text" />
						</td>
					</tr>
					
					
					<tr>
						<td class="label">
							<label for="WebsiteLink">Website Link</label>
						</td>
						<td class="value">
							<input type="text" name="WebsiteLink" id="WebsiteLink" 
							value="<?php echo $type11VO->getWebsiteLink() ?>" 
							class="input-text" />
							
							<label for="for example"> for example  (http://www.xyz.com)</label>
						</td>
						
						<!-- validate-clean-url  -->
					</tr>
					
					<?php if($this->getTableCode() != "apctwebsongs"): ?>
					<tr>
						<td class="label">
							<label for="HelpLineNumber">Land Line Number</label>
						</td>
						<td class="value">
							<input type="text" name="HelpLineNumber" id="HelpLineNumber" 
							value="<?php echo $type11VO->getHelpLineNumber() ?>" 
							class="validate-phoneLax input-text" />
						</td>
					</tr>
					
					 
							
							
					<tr>
						<td class="label">
							<label for="Email">Email</label>
						</td>
						<td class="value">
							<input type="text" name="Email" id="Email" 
							value="<?php echo $type11VO->getEmail() ?>" 
							class="validate-email input-text" />
						</td>
					</tr>
					
					<?php endif; ?>
					 
				
				
				
					<tr>
						<td class="label">
							<label for="StatusID">Status<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="StatusID" id="StatusID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($statusOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($type11VO->getStatusID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
							
							<input type="hidden" id="ID" name="ID" value="<?php echo ($type11VO->getID() != null) ? $type11VO->getID() : 0  ?>">
							<input type="hidden" id="TableName" name="TableName" value="<?php echo $this->getTableCode()  ?>">
							
							<?php if($this->getTableCode() == "apctwebsongs"): ?>
							<input type="hidden" id="HelpLineNumber" name="HelpLineNumber" value="">
							<input type="hidden" id="Email" name="Email" value="">
							<?php endif; ?>
							
						</td>
					</tr>
					
					  
					

					
				</tbody>
			</table>		
		  				
		</div>
	</div>
</div>