<?php
    $HTMLFormID = $this->getHTMLFormID();
    $systemConfigVO = $this->getSystemConfigVO();
    if($systemConfigVO == null){
    	$systemConfigVO = new Margshri_WebPortal_VO_Master_System_SystemConfigVO();
    }
    
    $statusOptions  = $this->getStatusOptions();

?>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">System Config</h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
					<tr>
						<td class="label">
							<label for="Config Name">Config Name<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="ConfigName" id="ConfigName" 
							value="<?php echo $systemConfigVO->getConfigName() ?>" 
							class="required-entry input-text" />
						</td>
					</tr>
					
					<tr>
						<td class="label">
							<label for="ConfigCode">Config Code<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="ConfigCode" id="ConfigCode" 
							value="<?php echo $systemConfigVO->getConfigCode() ?>" 
							class="required-entry input-text" />
						</td>
					</tr>
										 
					<tr>
						<td class="label">
							<label for="ConfigValue">Config Value<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="ConfigValue" id="ConfigValue" 
							value="<?php echo $systemConfigVO->getConfigValue() ?>" 
							class="required-entry input-text" />
						</td>
					</tr>
					
					
					<tr>
						<td class="label">
							<label for="StatusID">Status<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="StatusID" id="StatusID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($statusOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($systemConfigVO->getStatusID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
							
							<input type="hidden" id="ID" name="ID" value="<?php echo ($systemConfigVO->getID() > 0) ? $systemConfigVO->getID() : 0 ?>" />
						</td>
					</tr>
					
				</tbody>
			</table>
				
		</div>
	</div>
</div>