<?php
    $HTMLFormID = $this->getHTMLFormID();
    $attributeVO = $this->getAttributeVO();
    $typeOptions  = $this->getTypeOptions();
    $dataTypeOptions = $this->getDataTypeOptions();
    $statusOptions  = $this->getStatusOptions();
    
    if($attributeVO == null){
    	$attributeVO = new Margshri_WebPortal_VO_Master_SubPage_AttributeVO();
    }
?>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Sub Page Attribute</h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
				
					<tr>
						<td class="label">
							<label for="Value">Name<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="Value" id="Value" 
							value="<?php echo $attributeVO->getValue() ?>" 
							class="required-entry input-text" />
						</td>
					</tr>

					<tr>
						<td class="label">
							<label for="Code">Code<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="Code" id="Code" 
							value="<?php echo $attributeVO->getCode() ?>" 
							class="required-entry input-text" />
						</td>
					</tr>
					
					<tr>
						<td class="label">
							<label for="TypeID">Type<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="TypeID" id="TypeID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($typeOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($attributeVO->getTypeID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td class="label">
							<label for="DataTypeID">Data Type <span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="DataTypeID" id="DataTypeID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($dataTypeOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($attributeVO->getDataTypeID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td class="label">
							<label for="StatusID">Status<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="StatusID" id="StatusID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($statusOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($attributeVO->getStatusID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
							
							<input type="hidden" id="ID" name="ID" value="<?php echo ($attributeVO->getID() > 0) ? $attributeVO->getID() : 0 ?>" />
						</td>
					</tr>
					
				</tbody>
			</table>
				
				 
		</div>
	</div>
</div>