<?php
	
    $HTMLFormID = $this->getHTMLFormID();
    $viewerVO    = $this->getViewerVO();    
    
    if($viewerVO == null){
    	$viewerVO = new Margshri_WebPortal_VO_Center_Content_Type5_Viewer_ViewerVO();
    }
    
    $statusOptions  = $this->getStatusOptions();
    
?>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__("Viewer") ?></h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
		  	<table class="form-list">
					<tbody>
						
						<tr>
							<td class="label">
								<label for="StatusID">Status<span class="required">*</span></label>
							</td>
							<td class="value">
								<select name="StatusID" id="StatusID" class="validate-select">
									<option value="">--Select--</option>
									<?php foreach ($statusOptions as $key=>$value): ?>
										<option value="<?php echo $key ?>" <?php echo ($viewerVO->getStatusID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value ?></option>	
									<?php endforeach; ?>
								</select>
								<input type="hidden" id="ID" name="ID" value="<?php echo ($viewerVO->getID() != null) ? $viewerVO->getID() : 0  ?>">
							</td>
						</tr>
						
						
						
				  </table>
		</div>
	</div>
</div>