<?php
/* @var $callingReasonVO Dakiya_VO_Master_User_CallingReason_CallingReasonVO */ 
$callingReasonVO = $this->getCallingReasonVO();
if($callingReasonVO == null){
	$callingReasonVO = new Dakiya_VO_Master_User_CallingReason_CallingReasonVO();
}
?>

<div class="entry-edit">

	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Calling Reason</h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset ">
		<div class="hor-scroll">
			
			<table class="form-list">
				<tbody>
				
					<tr>
						<td class="label">
							<label for="TemplateName">Reason Name<span class="required">*</span></label>
						</td>
						<td class="value">
							<input id="ReasonName" name="ReasonName" value="<?php echo $callingReasonVO->getReasonName() ?>" 
							class="required-entry input-text" type="text" />
						</td>
					</tr>
					   
					
					<tr>
						<td class="label">
							<label for="Status">Status<span class="required">*</span></label>
						</td>
						<td class="value">
							<select id="StatusID" name="StatusID" class = "validate-select" >
								<option value="">--Select--</option>
								<?php foreach ($this->getStatusOptions() as $key=> $value): ?>
	     						<option value="<?php echo $key; ?>"  <?php  echo ( $key == $callingReasonVO->getStatusID()) ?   'selected="selected"' : '' ?> > <?php echo $value; ?> </option>
	     						<?php endforeach; ?>
	     					</select>
	     					<input id="ReasonID" name="ReasonID" value="<?php echo ($callingReasonVO->getReasonID() != null) ? $callingReasonVO->getReasonID() : 0  ?>" type="hidden" />
	     				</td>
	     			</tr>
					
					<tr>
						<td class="label">
							<label for="RoleIDs">Role Permission<span class="required">*</span></label>
						</td>
						<td class="value">
						
							<table class="form-list">
								<tbody>
									<tr>
								  		<?php $totalRows = sizeof($this->getAdminRoleOptions()) ?>
								  		<?php $totalCount= 0; ?>
								  		<?php $rowCount = 1; ?>
								  		<?php $administratorsRoleID = 1 ?>
							  			<?php foreach ($this->getAdminRoleOptions() as $key=> $value): ?>
							  				<?php $totalCount++ ?>
							  				<?php if($rowCount == 1): ?>
							  						<td >
							  				<?php endif; ?>
							  						<input type="checkbox" name="<?php echo $key ?>" id="<?php echo $key ?>" value="<?php echo $key ?>"
							  						 <?php echo ($key == $administratorsRoleID) ? "checked = 'checked' disabled = disabled " : ""  ?> >
							  						 <?php echo $value ?><br />
							  				<?php if($rowCount == floor($totalRows/5)  || $totalCount == $totalRows): ?>
							  						</td>
							  				<?php $rowCount = 1 ?>
							  				<?php continue; ?>
							  				<?php endif; ?>
							  				
							  				<?php $rowCount++ ?>
							  				
							  			<?php endforeach; ?>
							  				 
				  					 </tr>
				  				</tbody>
				  			</table>
						
						
							 
     					</td>
	     			</tr>
					
				</tbody>
			</table>
						 
		</div>
	</div>
</div>





 