<?php
    $HTMLFormID = $this->getHTMLFormID();
    /* @var $donationVO Margshri_Common_VO_Donation_Donation_DonationVO */
    $donationVO = $this->getDonationVO();    
    $adminUserID = Mage::getSingleton('admin/session')->getUser()->getId();
    // $cityOptions = $this->getCityOptions();
?>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-permissions-role"><?php echo ($this->getDonationID() != null ) ? ($this->__('Edit Member') ) : $this->__('Add Member') ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getBackButtonHtml() ?>
                <?php echo $this->getResetButtonHtml() ?>
                <?php echo $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>

<form action="<?php echo $this->getUrl('*/*/save') ?>" method="post" id="<?php echo $HTMLFormID ?>">
    <?php  echo $this->getBlockHtml('formkey')?>
    
    <div class="entry-edit">
    	<div class="entry-edit-head">
    		<h4 class="icon-head head-edit-form fieldset-legend">Member Detail</h4>
    		<div class="form-buttons"></div>
    	</div>
    
    	<div class="fieldset " id="base_fieldset">
    		<div class="hor-scroll">
    		   
      			<table class="form-list">
    				<tbody>
    
    					<tr>
							<td class="label">
								<label for="Donation Date">Date<span class="required">*</span>
							</label>
							</td>
							<td class="value"><input id="DonationDate"
								name="DonationDate" readonly="readonly"
								value="<?php echo ($donationVO->getDonationDate() != null && $donationVO->getDonationDate() != "0000-00-00" ) ? $donationVO->getDonationDate() : date("Y-m-d", Mage::getModel('core/date')->timestamp(time())) ?>"
								class="required-entry input-text" style="width: 275px;"
								type="text" /> <img
								src="<?php  echo Mage::getDesign()->getSkinUrl('images/grid-cal.gif') ?>"
								alt="" class="v-middle" id="DonationDateIMG"
								title="Select Date" style=""> 
								<script type="text/javascript">
	                                 //<![CDATA[ 
	                                 Calendar.setup({
	                                                  inputField: "DonationDate",
	                                                  ifFormat: "%Y-%m-%d",
	                                                  showsTime: 12,
	                                                  button: "DonationDateIMG",
	                                                  align: "Bl",
	                                                  onClose   : function() { this.hide(); return validationControl.dateTime(); },
	                                                  singleClick : true
	                                               });
                                    //]]> 
                                </script>
							</td>	
						</tr>
    
    					
    					<tr>
    						<td class="label">
    							<label for="DonorName">Member Name<span class="required">*</span>
    						</td>
    						<td class="value">
    							<input type="text" name="DonorName" id="DonorName" value="<?php echo $donationVO->getDonorName() ?>" class="input-text" />
    						</td>
    					</tr>
    					
    					
    					<tr>
    						<td class="label">
    							<label for="FatherName">Father/Husband Name</label>
    						</td>
    						<td class="value">
    							<input type="text" name="FatherName" id="FatherName" value="<?php echo $donationVO->getFatherName() ?>" class="input-text" />
    						</td>
    					</tr>
    					
    					<?php $genderOptions = array("Male"=>"Male", "Female"=>"Female"); ?>
    					<tr>
    						<td class="label">
    							<label for="Description">Gender<span class="required">*</span>
    						</td>
    						<td class="value">
    							<select name="Description" id="Description" >
    								<option value="">--Select--</option>
    								<?php foreach ($genderOptions as $genderID=>$genderName): ?>
    										<option value="<?php echo $genderID ?>" <?php echo ($genderID == trim($donationVO->getDescription()) ) ? 'selected="selected"' : '' ?> ><?php echo $genderName ?></option>
    								<?php endforeach; ?>
    							</select>
    						</td>
    					</tr>
    					
    					
    					<tr>
    						<td class="label">
    							<label for="ContactNumber">Mobile Number</label>
    						</td>
    						<td class="value">
    							<input type="text" name="ContactNumber" id="ContactNumber" maxlength="10"
    							value="<?php echo $donationVO->getContactNumber() ?>" 
    							class="input-text validate-digits" />
    						</td>
    					</tr>
    					
    					
    					 
    					
    					
    					<tr>
    						<td class="label">
    							<label for="ReceiptBookID">Receipt Book<span class="required">*</span>
    						</td>
    						<td class="value">
    							<select name="ReceiptBookID" id="ReceiptBookID" <?php echo ($adminUserID != 1) ? 'disabled="disabled"' : '' ?> >
    								<option value="">--Select--</option>
    								<?php foreach ($this->getReceiptBookOptions() as $receiptBookID=>$receiptBookName): ?>
    								
    									<?php $selected = ''; ?>
    									<?php if($adminUserID != 1): ?>
    										<?php $selected = 'Selected = "Selected"'; ?>
    									<?php elseif($donationVO->getReceiptBookID() == $receiptBookID): ?>
    										<?php $selected = 'Selected = "Selected"'; ?>
    									<?php else: ?>
    										
    									<?php endif; ?>
    									<option value="<?php echo $receiptBookID ?>" <?php echo $selected ?> ><?php echo $receiptBookName ?></option>
    								<?php endforeach; ?>
    							</select>
    						</td>
    					</tr>
    					
    					
    					<tr>
    						<td class="label">
    							<label for="ReceiptNumber">Receipt Number<span class="required">*</span>
    						</td>
    						<td class="value">
    							<input type="text" name="ReceiptNumber" id="ReceiptNumber" 
    							value="<?php echo $donationVO->getReceiptNumber() ?>" 
    							class="input-text" />
    						</td>
    					</tr>
    					
    					
    					<tr>
    						<td class="label">
    							<label for="DonatedAmount">Amount<span class="required">*</span>
    						</td>
    						<td class="value">
    							<input type="text" name="DonatedAmount" id="DonatedAmount" 
    							value="<?php echo ($donationVO->getID() == null) ? 10 : $donationVO->getDonatedAmount() ?>" 
    							class="input-text" disabled="disabled" />
    						</td>
    					</tr>
    					
    					
    					<tr>
    						<td class="label">
    							<label for="Address">Address<span class="required">*</span>
    						</td>
    						
							<td class="value">
								<textarea rows="3" cols="10" name="Address" id="Address" style="height: 40px;" ><?php echo $donationVO->getAddress() ?></textarea>
							</td>
	   						
    					</tr>
    					
    					
    					
    				</tbody>
    			</table>		
    		  		 
    			
    		</div>
    	</div>
    </div>
    
    <input type="hidden" id="ID" name="ID" value="<?php echo ($donationVO->getID() != null && $donationVO->getID() != "") ? $donationVO->getID() : 0 ?>" />
</form>

<script type="text/javascript">

function donationVO(){
	this.ID = null;
	this.DonorName = null;
	this.ContactNumber = null;
	this.Address = null;
	this.UserID = null;
	this.DonationTypeID = null;
	this.ReceiptBookID = null;
	this.ReceiptNumber = null;
	this.DonatedAmount = null;
	this.DonationYear = null;
	this.DonationDate = null;
	this.DonationTime = null;
	this.Description = null;
	this.StatusID = null;
}
var newDonationDTO = new donationVO();

var donationFormObj = new varienForm('<?php echo $HTMLFormID; ?>');
var donationFormJS={

		submit : function(){
    		if(!donationFormJS.saveValidation()) return ;
    			donationFormJS.saveAjax();
		},

		saveValidation : function(){
			
         	if(!(donationFormObj.validator && donationFormObj.validator.validate())){
    	    	return false;
	    	}
         	
         	// SET VOs
         	newDonationDTO.ID = ($('ID').value).strip();
         	newDonationDTO.DonorName = ($('DonorName').value).strip();
         	newDonationDTO.FatherName = ($('FatherName').value).strip();
         	newDonationDTO.ContactNumber = ($('ContactNumber').value).strip();
         	newDonationDTO.Address = ($('Address').value).strip();
         	
         	newDonationDTO.ReceiptBookID = ($('ReceiptBookID').value).strip();
         	newDonationDTO.ReceiptNumber = ($('ReceiptNumber').value).strip();
         	newDonationDTO.DonatedAmount = ($('DonatedAmount').value).strip();
         	newDonationDTO.DonationDate = ($('DonationDate').value).strip();

         	newDonationDTO.Description = ($('Description').value).strip();
         	   

         	if(newDonationDTO.DonorName == null || newDonationDTO.DonorName == ""){
				alert("Please Enter Member Name.");
				$("DonorName").focus();
				return false;
			}

         	
         	if(newDonationDTO.ReceiptBookID == null || newDonationDTO.ReceiptBookID == ""){
				alert("Please Select Receipt Book .");
				$("ReceiptBookID").focus();
				return false;
			}


         	if(newDonationDTO.ReceiptNumber == null || newDonationDTO.ReceiptNumber == ""){
				alert("Please Enter Receipt Number.");
				$("ReceiptNumber").focus();
				return false;
			}

         	if(newDonationDTO.DonatedAmount == null || newDonationDTO.DonatedAmount == ""){
				alert("Please Enter Receipt Amount.");
				$("DonatedAmount").focus();
				return false;
			}

         	if(newDonationDTO.DonationDate == null || newDonationDTO.DonationDate == ""){
				alert("Please Enter Date.");
				$("DonationDate").focus();
				return false;
			}

         	if(newDonationDTO.Address == null || newDonationDTO.Address == ""){
				alert("Please Enter Address.");
				$("Address").focus();
				return false;
			}

         	if(newDonationDTO.Description == null || newDonationDTO.Description == ""){
				alert("Please Select Gender.");
				$("Description").focus();
				return false;
			}
         	
         	 
         	return true;
		},	

        saveAjax: function(){
        	var URL = "<?php echo $this->getUrl('*/*/save')?>" ;
		    var parameters= {"DonationDataObj": JSON.stringify(newDonationDTO,null) };
		    var callBackMethod ="donationFormJS.responseSave";
		    var callBackArgs =null;
		    ajaxRequest.execute(	URL, parameters, callBackMethod , callBackArgs );
		    return false;
     	},

	    responseSave : function(response,args) {
	    	if(response.SuccessMessage !=null){
	    		window.location.href = "<?php echo $this->getUrl('*/*/index')?>";
			 	return;
			}else if(response.ErrorMessage !=null){
				alert(response.ErrorMessage);
				return false;
 			}
 	 	}
			
}; 
 

</script>    	 
