<?php
    $HTMLFormID = $this->getHTMLFormID();
    $bidProductsVO = $this->getBidProductsVO();
    $bidOptions = $this->getBidOptions();
    $productOptions = $this->getProductOptions();
    $statusOptions  = $this->getStatusOptions();
    //$getYesNoOptions  = $this->getYesNoOptions();
    
    if($bidProductsVO == null){
    	$bidProductsVO = new Margshri_WebPortal_VO_Master_Right_BidProductsVO();
    }
?>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Bidding</h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
					  
					<tr>
						<td class="label">
							<label for="BidID">Bid List<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="BidID" id="BidID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($bidOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($bidProductsVO->getBidID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td class="label">
							<label for="ProductID">Product List<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="ProductID" id="ProductID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($productOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($bidProductsVO->getProductID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td class="label">
							<label for="StatusID">Status<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="StatusID" id="StatusID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($statusOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($bidProductsVO->getStatusID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
							
							<input type="hidden" id="ID" name="ID" value="<?php echo ($bidProductsVO->getID() > 0) ? $bidProductsVO->getID() : 0 ?>" />
						</td>
					</tr>
					
				</tbody>
			</table>
				
				 
				
		</div>
	</div>
</div>