<?php
$HTMLFormID = $this->getHTMLFormID();
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            
            <td style="width:50%;"><h3 class="icon-head head-permissions-role"><?php echo ($this->getID() != null ) ? ($this->__('Edit') ) : $this->__('Add') ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getBackButtonHtml() ?>
                <?php echo $this->getResetButtonHtml() ?>
                <?php echo $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>

<form action="<?php echo $this->getUrl('*/*/save') ?>" method="post" id="<?php echo $HTMLFormID ?>">
    <?php  echo $this->getBlockHtml('formkey')?>
    <?php  echo $this->getEntropy()?>
</form>

<script type="text/javascript">

function HospitalVO(){
	this.ID = null;
	this.Value = null;
	this.Code = null;
	this.UserID = null;
	this.Order = null;
	this.WebsiteLink = null;
	this.IsPaid = null;

	this.TinNumber = null;
	this.PANNumber = null;
	this.Category1ID = null;
	this.Category1Value = null;
	this.Category2ID = null;
	this.Category2Value = null;
	this.Category3ID = null;
	this.Category3Value = null;
	this.HospitalTypeID = null;
	this.StatusID=null;
	this.LandLineNumber=null;
	this.MobileNumber1=null;
	this.MobileNumber2=null;
	this.Email=null;
	this.PinCode=null;
	this.Address = null;
	this.CountryID = null;
	this.StateID = null;
	this.DistrictID=null;
	this.CityID=null;
	
}
var newHospitalDTO = new HospitalVO();

var formObj = new varienForm('<?php echo $HTMLFormID; ?>');
var formJS={

		submit : function(){
    		if(!formJS.saveValidation()) return ;
				formJS.saveAjax();
		},

		saveValidation : function(){
			var errorMsg = '';

         	if(!(formObj.validator && formObj.validator.validate())){
    	    	return false;
	    	}
         	
         	// SET VOs 
         	newHospitalDTO.ID = ($('ID').value).strip();
         	newHospitalDTO.Value = ($('Value').value).strip();
         	newHospitalDTO.Code = null;
         	newHospitalDTO.UserID = null;
         	newHospitalDTO.Order = null;
         	newHospitalDTO.WebsiteLink = ($('WebsiteLink').value).strip();

			if($("IsPaid").checked == true){
				newHospitalDTO.IsPaid = 1;
			}else{
				newHospitalDTO.IsPaid = 0;
			}
         	
         	newHospitalDTO.TinNumber = ($('TinNumber').value).strip();
         	newHospitalDTO.PANNumber = ($('PANNumber').value).strip();
         	newHospitalDTO.Category1ID = ($('Category1ID').value).strip();
         	newHospitalDTO.Category1Value = ($('Category1Value').value).strip();
         	newHospitalDTO.Category2ID = ($('Category2ID').value).strip();
         	newHospitalDTO.Category2Value = ($('Category2Value').value).strip();
         	newHospitalDTO.Category3ID = ($('Category3ID').value).strip();
         	newHospitalDTO.Category3Value = ($('Category3Value').value).strip();
         	newHospitalDTO.HospitalTypeID = ($('HospitalTypeID').value).strip();
         	newHospitalDTO.StatusID = ($('StatusID').value).strip();
         	newHospitalDTO.LandLineNumber = ($('LandLineNumber').value).strip();
         	newHospitalDTO.MobileNumber1 = ($('MobileNumber1').value).strip();
         	newHospitalDTO.MobileNumber2 = ($('MobileNumber2').value).strip();
         	newHospitalDTO.Email = ($('Email').value).strip();

         	newHospitalDTO.PinCode = ($('PinCode').value).strip();
         	
         	newHospitalDTO.Address = ($('Address').value).strip();
         	newHospitalDTO.CountryID = ($('CountryID').value).strip();
         	newHospitalDTO.StateID = ($('StateID').value).strip();
         	newHospitalDTO.DistrictID = ($('DistrictID').value).strip();
         	newHospitalDTO.CityID = ($('CityID').value).strip();


         	if($('Category1Value').style.display != 'none'){
             	if(newHospitalDTO.Category1Value == '' || newHospitalDTO.Category1Value == null)
         			errorMsg += "Please Enter First Category Value \n"; 
            }else{
            	newHospitalDTO.Category1ID = null;
            }

         	if($('Category2Value').style.display != 'none'){
             	 if(newHospitalDTO.Category2Value == '' || newHospitalDTO.Category2Value == null)
         		errorMsg += "Please Enter Second Category Value \n"; 
            }else{
            	newHospitalDTO.Category2ID = null;
            }

            if($('Category3Value').style.display != 'none'){
              	 if(newHospitalDTO.Category3Value == '' || newHospitalDTO.Category3Value == null)
	           		errorMsg += "Please Enter Third Category Value \n"; 
            }else{
               	newHospitalDTO.Category3ID = null;
            }


            if(newHospitalDTO.MobileNumber1 != null && newHospitalDTO.MobileNumber1 != '' &&
            		newHospitalDTO.MobileNumber2 != null && newHospitalDTO.MobileNumber2 != ''){
            
	            if(newHospitalDTO.MobileNumber1 == newHospitalDTO.MobileNumber2){
					$('MobileNumber2').value = "";
					$('MobileNumber2').focus();
					errorMsg += "Both Mobile Number Can`t Be Same ! \n";
				}
            }	

            if(newHospitalDTO.WebsiteLink != null && newHospitalDTO.WebsiteLink != ''){
				var re = new RegExp("^http(s?)\:\/\/[0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*(:(0-9)*)*(\/?)([a-zA-Z0-9\-\.\?\,\'\/\\\+&amp;%\$#_]*)?$");
	         	if (!re.test(newHospitalDTO.WebsiteLink)) { 
	         		errorMsg = "Invalid Website Link ! \n";
	         	}
		    }	
			
            
         	
         	if(errorMsg != ''){
            	alert(errorMsg);
				return false;
			}

			return true;	
		},	

        saveAjax: function(){
        	var URL = "<?php echo $this->getUrl('*/*/save')?>" ;
		    var parameters= {"HospitalDataObj": JSON.stringify(newHospitalDTO,null) };
		    var callBackMethod ="formJS.responseSave";
		    var callBackArgs =null;
		    ajaxRequest.execute(	URL, parameters, callBackMethod , callBackArgs );
		    return false;
     	},

	    responseSave : function(response,args) {
        	if(response.SuccessMessage !=null){
			 	window.location.href = "<?php echo $this->getUrl('*/*/index')?>" ;
			 	return;
			}else if(response.ErrorMessage !=null){
				alert(response.ErrorMessage);
    			return false;
 			}
 	 	},
		
		setDistrictList: function(stateID){
			//var stateID = obj.value;
			var innerHTML = '<option value="">--Select--</option>';
			for(var key in districtList){
				if(districtList[key].StateID == stateID){
					if(key == HOSPITALVO.DistrictID)
						innerHTML += '<option value="'+key+'" selected = "selected">'+districtList[key].Name+'</option>';
					else
						innerHTML += '<option value="'+key+'">'+districtList[key].Name+'</option>';	
				}
			}
			UI.elementDisabled($('DistrictID'), false);
			$('DistrictID').innerHTML = innerHTML;
			return; 
		},

		setCityList: function(districtID){
			//var districtID = obj.value;
			var innerHTML = '<option value="">--Select--</option>';
			for(var key in cityList){
				if(cityList[key].DistrictID == districtID){
					if(key == HOSPITALVO.CityID)
						innerHTML += '<option value="'+key+'" selected = "selected">'+cityList[key].Name+'</option>';
					else		
						innerHTML += '<option value="'+key+'">'+cityList[key].Name+'</option>';
				}
			}
			UI.elementDisabled($('CityID'), false);
			$('CityID').innerHTML = innerHTML;
			return; 
		},

		setCategoryBox: function(obj){
			var categoryID   = obj.value;
			var categoryName = obj.name;
			var categoryValueID; 

			switch(categoryName){
				case 'Category1ID':
					categoryValueID = 'Category1Value';	
					break;
				case 'Category2ID':
					categoryValueID = 'Category2Value';
					break;
				case 'Category3ID':
					categoryValueID = 'Category3Value';
					break;		 
			}
			
			if(categoryID != ''){
				UI.elementVisibility($(categoryValueID),"block");
			}else{
				UI.elementVisibility($(categoryValueID),"none");
				$(categoryValueID).value = '';
			}			
			return false;			 
		},
		

		defaultSetting: function(){
			UI.elementDisabled($('DistrictID'), true);
			UI.elementDisabled($('CityID'), true);

			UI.elementVisibility($("Category1Value"),"none");
			UI.elementVisibility($("Category2Value"),"none");
			UI.elementVisibility($("Category3Value"),"none");
		}
			
}; 


// FOR EDIT 
if(HOSPITALVO != ''){

	if(HOSPITALVO.Category1Value != '' && HOSPITALVO.Category1Value != null){
		UI.elementVisibility($("Category1Value"),"block");
	}else{
		UI.elementVisibility($("Category1Value"),"none");
	}

	if(HOSPITALVO.Category2Value != '' && HOSPITALVO.Category2Value != null ){
		UI.elementVisibility($("Category2Value"),"block");
	}else{
		UI.elementVisibility($("Category2Value"),"none");
	}

	if(HOSPITALVO.Category3Value != '' && HOSPITALVO.Category3Value != null){
		UI.elementVisibility($("Category3Value"),"block");
	}else{
		UI.elementVisibility($("Category3Value"),"none");
	}

	
	formJS.setDistrictList(HOSPITALVO.StateID);
	formJS.setCityList(HOSPITALVO.DistrictID);		
	
}else{
	formJS.defaultSetting();
}

</script>