<?php
    $HTMLFormID = $this->getHTMLFormID();
    $branchVO   = $this->getBranchVO();
    $bankVOs    = $this->getBankVOs();
    
    if($branchVO == null){
    	$branchVO = new Margshri_WebPortal_VO_Center_Content_Type1_Bank_BranchVO();
    }
    
    $countryOptions = $this->getCountryOptions();
    $stateOptions   = $this->getStateOptions();
    $districtOptions= $this->getDistrictOptions();
    $cityOptions    = $this->getCityOptions();
    $statusOptions  = $this->getStatusOptions();
?>
<script type="text/javascript">
<!--

//SET STATE 
var stateList = '';
var stateOptions = '<?php echo (sizeof($stateOptions) > 0) ?  json_encode($stateOptions) : '' ?>';
if(stateOptions != ''){
	stateList = JSON.parse(stateOptions);	
}

//SET DISTRICT 
var districtList = '';
var districtOptions = '<?php echo (sizeof($districtOptions) > 0) ?  json_encode($districtOptions) : '' ?>';
if(districtOptions != ''){
	districtList = JSON.parse(districtOptions);	
}

//SET STATE 
var cityList = '';
var cityOptions = '<?php echo (sizeof($cityOptions) > 0) ?  json_encode($cityOptions) : '' ?>';
if(cityOptions != ''){
	cityList = JSON.parse(cityOptions);	
}

//SET STATE 
var BRANCHVO = '';
var branchDTO = '<?php echo ($branchVO->getID() != null) ? json_encode($branchVO->getDataArray()) : '' ?>';
if(branchDTO != ''){
	BRANCHVO = JSON.parse(branchDTO);
}

//-->
</script>


<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Bank Branch </h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
		  <table style="">
		  	<tr>
		  		<td>
		  			<table class="form-list">
						<tbody>
							<tr>
								<td class="label">
									<label for="Value">Branch Name<span class="required">*</span></label>
								</td>
								<td class="value">
									<input type="text" name="Value" id="Value" 
									value="<?php echo $branchVO->getValue() ?>" 
									class="required-entry input-text" />
								</td>
							</tr>
							
							<tr>
								<td class="label">
									<label for="Code">Branch Code<span class="required">*</span></label>
								</td>
								<td class="value">
									<input type="text" name="Code" id="Code" 
									value="<?php echo $branchVO->getCode() ?>" 
									class="required-entry input-text" />
								</td>
							</tr>
							
							
							<tr>
								<td class="label">
									<label for="Address">Address<span class="required">*</span></label>
								</td>
								<td class="value">
									<textarea rows="3" cols="10" name="Address" id="Address" class="required-entry" style="height: 40px;" ><?php echo $branchVO->getAddress() ?></textarea>
								</td>
							</tr>
		
							<tr>
								<td class="label">
									<label for="CountryID">Country<span class="required">*</span></label>
								</td>
								<td class="value">
									<select name="CountryID" id="CountryID" disabled="disabled">
										<!--  <option>--Select--</option> -->
										<?php foreach ($countryOptions as $key=>$value): ?>
											<option value="<?php echo $key ?>" selected="selected"><?php echo $value ?></option>	
										<?php endforeach; ?>
									</select>
								</td>
							</tr>
							
							<tr>
								<td class="label">
									<label for="StateID">State<span class="required">*</span></label>
								</td>
								<td class="value">
									<select name="StateID" id="StateID" onchange="formJS.setDistrictList(this.value)" class="validate-select">
										<option value="">--Select--</option>
										<?php foreach ($stateOptions as $key=>$value): ?>
											<option value="<?php echo $key ?>" <?php echo ($branchVO->getStateID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value['Name'] ?></option>	
										<?php endforeach; ?>
									</select>
								</td>
							</tr>
							
							<tr>
								<td class="label">
									<label for="DistrictID">District<span class="required">*</span></label>
								</td>
								<td class="value">
									<select name="DistrictID" id="DistrictID" onchange="formJS.setCityList(this.value)"  class="validate-select">
										<option value="">--Select--</option>
									</select>
								</td>
							</tr>
							
							<tr>
								<td class="label">
									<label for="CityID">City<span class="required">*</span></label>
								</td>
								<td class="value">
									<select name="CityID" id="CityID" class="validate-select">
										<option value="">--Select--</option>
									</select>
								</td>
							</tr>
							
							<tr>
								<td class="label">
									<label for="PinCode">PinCode</label>
								</td>
								<td class="value">
									<input type="text" name="PinCode" id="PinCode" 
									value="<?php echo $branchVO->getPinCode() ?>" 
									class="validate-number input-text" />
								</td>
							</tr>
							
						</tbody>
					</table>		
		  		</td>	
		  	
		  		<td style="width: 200px;"></td>
		  	
		  		<td>
					<table class="form-list">
						<tbody>
						
							<tr>
								<td class="label">
									<label for="IFSCCode">IFSC Code<span class="required">*</span></label>
								</td>
								<td class="value">
									<input type="text" name="IFSCCode" id="IFSCCode" 
									value="<?php echo $branchVO->getIFSCCode() ?>" 
									class="required-entry input-text" />
								</td>
							</tr>
							
							<tr>
								<td class="label">
									<label for="MICRCode">MICR Code<span class="required">*</span></label>
								</td>
								<td class="value">
									<input type="text" name="MICRCode" id="MICRCode" 
									value="<?php echo $branchVO->getMICRCode() ?>" 
									class="required-entry input-text" />
								</td>
							</tr>
							
							
							
							<tr>
								<td class="label">
									<label for="BankID">Bank<span class="required">*</span></label>
								</td>
								<td class="value">
									<select name="BankID" id="BankID" class="validate-select">
										<option value="" >--Select--</option>
										
										<?php foreach ($bankVOs as $bankVO): ?>
											<option value="<?php echo $bankVO->getID() ?>" <?php echo ($branchVO->getBankID() == $bankVO->getID() ) ? 'selected="selected"' : '' ?> ><?php echo ($bankVO->getCode() != null) ? $bankVO->getValue() . '  (' . $bankVO->getCode() . ')' : $bankVO->getValue() ?></option>	
										<?php endforeach; ?>
									</select>
								</td>
							</tr>
							
							<tr>
								<td class="label">
									<label for="WebsiteLink">Website Link</label>
								</td>
								<td class="value">
									<input type="text" name="WebsiteLink" id="WebsiteLink" 
									value="<?php echo $branchVO->getWebsiteLink() ?>" 
									class="input-text" />
								</td>
							</tr>
							 
							<tr>
								<td class="label">
									<label for="LandLineNumber">Land Line Number</label>
								</td>
								<td class="value">
									<input type="text" name="LandLineNumber" id="LandLineNumber" 
									value="<?php echo $branchVO->getLandLineNumber() ?>" 
									class="validate-phoneLax input-text" />
								</td>
							</tr>
							
							
							<tr>
								<td class="label">
									<label for="MobileNumber1">Mobile Number 1</label></label>
								</td>
								<td class="value">
									<input type="text" name="MobileNumber1" id="MobileNumber1" 
									value="<?php echo $branchVO->getMobileNumber1() ?>" 
									class="input-text validate-mobileno" />
								</td>
							</tr>
							
							
							<tr>
								<td class="label">
									<label for="MobileNumber2">Mobile Number 2</label>
								</td>
								<td class="value">
									<input type="text" name="MobileNumber2" id="MobileNumber2" 
									value="<?php echo $branchVO->getMobileNumber2() ?>" 
									class="input-text validate-mobileno" />
								</td>
							</tr>
									
									
							<tr>
								<td class="label">
									<label for="Email">Email</label>
								</td>
								<td class="value">
									<input type="text" name="Email" id="Email" 
									value="<?php echo $branchVO->getEmail() ?>" 
									class="validate-email input-text" />
								</td>
							</tr>	
						
						
							<tr>
								<td class="label">
									<label for="StatusID">Status<span class="required">*</span></label>
								</td>
								<td class="value">
									<select name="StatusID" id="StatusID" class="validate-select">
										<option value="">--Select--</option>
										<?php foreach ($statusOptions as $key=>$value): ?>
											<option value="<?php echo $key ?>" <?php echo ($branchVO->getStatusID() == $key ) ? 'selected="selected"' : '' ?> ><?php echo $value ?></option>	
										<?php endforeach; ?>
									</select>
									<input type="hidden" id="ID" name="ID" value="<?php echo ( $branchVO->getID() != null ) ? $branchVO->getID() : 0 ?>">
								</td>
							</tr>
		
		

							
							
							
							
						</tbody>
					</table>  		
		  		</td>
		  	</tr>
		  </table>
			
		</div>
	</div>
</div>