<?php
$HTMLFormID = $this->getHTMLFormID();
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            
            <td style="width:50%;"><h3 class="icon-head head-permissions-role"><?php echo ($this->getID() != null ) ? ($this->__('Edit Bank Branch ') ) : $this->__('Create Bank Branch') ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getBackButtonHtml() ?>
                <?php echo $this->getResetButtonHtml() ?>
                <?php echo $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>

<form action="<?php echo $this->getUrl('*/*/save') ?>" method="post" id="<?php echo $HTMLFormID ?>">
    <?php  echo $this->getBlockHtml('formkey')?>
    <?php  echo $this->getEntropy()?>
</form>

<script type="text/javascript">

function branchVO(){
	this.ID = null;
	this.Value = null;
	this.Code = null;
	this.UserID = null;
	this.Order = null;
	this.WebsiteLink = null;
	this.IsPaid = null;
	this.IFSCCode = null;
	this.MICRCode = null;
	this.BankID = null;	
	this.StatusID=null;
	this.LandLineNumber=null;
	this.MobileNumber1=null;
	this.MobileNumber2=null;
	this.Email=null;
	this.PinCode=null;
	this.Address = null;
	this.CountryID = 1;
	this.StateID = null;
	this.DistrictID=null;
	this.CityID=null;
}
var newBranchDTO = new branchVO();

var formObj = new varienForm('<?php echo $HTMLFormID; ?>');
var formJS={

		submit : function(){
    		if(!formJS.saveValidation()) return ;
				formJS.saveAjax();
		},

		saveValidation : function(){
			var errorMsg = '';

			
         	if(!(formObj.validator && formObj.validator.validate())){
    	    	return false;
	    	}
	    	

         	// SET VOs 
         	newBranchDTO.ID = ($('ID').value).strip();
         	newBranchDTO.Value = ($('Value').value).strip();
         	newBranchDTO.Code = ($('Code').value).strip();
         	newBranchDTO.UserID = null;
         	newBranchDTO.Order = null;
         	newBranchDTO.WebsiteLink = ($('WebsiteLink').value).strip();
         	newBranchDTO.IsPaid = 0;         	
         	newBranchDTO.IFSCCode = ($('IFSCCode').value).strip();
         	newBranchDTO.MICRCode = ($('MICRCode').value).strip();
         	newBranchDTO.BankID = ($('BankID').value).strip();
         	newBranchDTO.StatusID = ($('StatusID').value).strip();
         	newBranchDTO.LandLineNumber = ($('LandLineNumber').value).strip();
         	newBranchDTO.MobileNumber1 = ($('MobileNumber1').value).strip();
         	newBranchDTO.MobileNumber2 = ($('MobileNumber2').value).strip();
         	newBranchDTO.Email = ($('Email').value).strip();
         	newBranchDTO.PinCode = ($('PinCode').value).strip();
         	newBranchDTO.Address = ($('Address').value).strip();
         	newBranchDTO.CountryID = ($('CountryID').value).strip();
         	newBranchDTO.StateID = ($('StateID').value).strip();
         	newBranchDTO.DistrictID = ($('DistrictID').value).strip();
         	newBranchDTO.CityID = ($('CityID').value).strip();

         	if( (newBranchDTO.LandLineNumber == null || newBranchDTO.LandLineNumber == '') && (newBranchDTO.MobileNumber1 == null || newBranchDTO.MobileNumber1 == '') ){
         		errorMsg += 'Please Enter Land Line Number OR Mobile Number1 \n';
         	}
         	
         	if(errorMsg != ''){
            	alert(errorMsg);
				return false;
			}

			return true;	
		},	

        saveAjax: function(){
        	var URL = "<?php echo $this->getUrl('*/*/save')?>" ;
		    var parameters= {"BranchDataObj": JSON.stringify(newBranchDTO,null) };
		    var callBackMethod ="formJS.responseSave";
		    var callBackArgs =null;
		    ajaxRequest.execute(	URL, parameters, callBackMethod , callBackArgs );
		    return false;
     	},

	    responseSave : function(response,args) {
        	if(response.SuccessMessage !=null){
			 	window.location.href = "<?php echo $this->getUrl('*/*/index')?>";
			 	return;
			}else if(response.ErrorMessage !=null){
				alert(response.ErrorMessage);
    			return false;
 			}
 	 	},
		
		setDistrictList: function(stateID){
			//var stateID = obj.value;
			var innerHTML = '<option value="">--Select--</option>';
			for(var key in districtList){
				if(districtList[key].StateID == stateID){
					if(key == BRANCHVO.DistrictID)
						innerHTML += '<option value="'+key+'" selected = "selected">'+districtList[key].Name+'</option>';
					else
						innerHTML += '<option value="'+key+'">'+districtList[key].Name+'</option>';	
				}
			}
			UI.elementDisabled($('DistrictID'), false);
			$('DistrictID').innerHTML = innerHTML;
			return; 
		},

		setCityList: function(districtID){
			//var districtID = obj.value;
			var innerHTML = '<option value="">--Select--</option>';
			for(var key in cityList){
				if(cityList[key].DistrictID == districtID){
					if(key == BRANCHVO.CityID)
						innerHTML += '<option value="'+key+'" selected = "selected">'+cityList[key].Name+'</option>';
					else		
						innerHTML += '<option value="'+key+'">'+cityList[key].Name+'</option>';
				}
			}
			UI.elementDisabled($('CityID'), false);
			$('CityID').innerHTML = innerHTML;
			return; 
		},

		defaultSetting: function(){
			UI.elementDisabled($('DistrictID'), true);
			UI.elementDisabled($('CityID'), true);
		}
			
}; 


// FOR EDIT 

if(BRANCHVO != ''){
	
	formJS.setDistrictList(BRANCHVO.StateID);
	formJS.setCityList(BRANCHVO.DistrictID);		
	
}else{
	formJS.defaultSetting();
}



</script>