<?php
    $HTMLFormID = $this->getHTMLFormID();
    $tableTypeVO = $this->getTableTypeVO();
    $statusOptions  = $this->getStatusOptions();
    
    if($tableTypeVO == null){
    	$tableTypeVO = new Margshri_WebPortal_VO_Master_Table_TableTypeVO();
    }
?>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Web Table Type</h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
					<tr>
						<td class="label">
							<label for="Value">Name<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="Value" id="Value" 
							value="<?php echo $tableTypeVO->getValue() ?>" 
							class="required-entry input-text" />
						</td>
					</tr>
					
					<tr>
						<td class="label">
							<label for="Code">Code<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="Code" id="Code" 
							value="<?php echo $tableTypeVO->getCode() ?>" 
							class="required-entry input-text" />
						</td>
					</tr>
					

					<tr>
						<td class="label">
							<label for="Discription">Discription</label>
						</td>
						<td class="value">
							<textarea rows="5" cols="10" id="Discription" name="Discription" ><?php echo $tableTypeVO->getDiscription() ?></textarea>
						</td>
					</tr>

					
					<tr>
						<td class="label">
							<label for="StatusID">Status<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="StatusID" id="StatusID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($statusOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($tableTypeVO->getStatusID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
							
							<input type="hidden" id="ID" name="ID" value="<?php echo ($tableTypeVO->getID() > 0) ? $tableTypeVO->getID() : 0 ?>" />
						</td>
					</tr>
					
					
				</tbody>
			</table>
		</div>
	</div>
</div>