<?php
$bloodDonationVOs = $this->getBloodDonorVOs();
$totalDonor = sizeof($bloodDonationVOs);

 
 
?>

<div class="card bg-light text-dark" style="margin: 50px 0px 10px 0px !important;">
	<div class="card-body" style="padding:0px !important;">
		<table class="table" style="margin-bottom: 0px !important;">
			<tbody>
				<tr>
					<td style="border-top:none; width: 20% !important;" class="text-left">
						<span style="font-size:20px;" onclick="baseFormJS.redirect('<?php echo $this->getUrl('common/Frontend_Donor_Donor/showBloodDonorFilterForm') ?>')">&laquo;</span> 
					</td>
					
					<td style="border-top:none; vertical-align: middle;" class="text-center">
						<span style="font-weight:bold;">Blood Donor List</span>
					</td>
					
					<td style="border-top:none; width: 20% !important; vertical-align: middle; " class="text-left">
						<span style="font-weight:bold;"><?php echo $totalDonor; ?></span>	
					</td>
				</tr>
			</tbody>
		</table>
	</div>
	
	<div class="card-body" style="padding:0px !important;">
		<table class="table" style="margin-bottom: 0px !important;">
			<tbody>
				<tr>
					<td style="border-top:none; vertical-align: middle;" class="text-center">
						<input class="form-control" id="Search" type="text" placeholder="Search..">
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

<div class="card bg-light">
    <div class="card-body" id="DonorContainer" style="padding: unset !important;" >
    <?php if($totalDonor > 0):?>
        <?php $counter = 0; ?>
        <ul class="list-group" id="DonorList">
        <?php foreach($bloodDonationVOs as $bloodDonationVO): ?>
        	 
        	<?php $counter++;?>
        	<li class="list-group-item p-1 ">
            	<div class="media">
            		<div class="m-1 rounded text-center" style="width:50px;">
                <?php if($bloodDonationVO['UserImageURL'] != null && $bloodDonationVO['UserImageURL'] != "" ): ?>
                	 <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $bloodDonationVO['UserImageURL'] ?>" alt="donor" class="rounded text-center" style="width:50px;">
                <?php else: ?>
                	 <i class="fa fa-user" style="font-size:50px"></i>
                <?php endif; ?>
                	</div>
            
                    <div class="media-body text-left">
                        <p style="margin-bottom: 0px !important;" ><small><b><?php echo ($bloodDonationVO['Name'] != null && $bloodDonationVO['Name'] != "") ?  ucwords(strtolower($bloodDonationVO['NamePrefix'] . " " . $bloodDonationVO['Name'])) : ''  ?></b></small></p>
                        <!--  
                        <p style="margin-bottom: 0px !important; font-size: 7pt !important; font-style: italic;"><?php // echo ($userVO->getParentName() != null && $userVO->getParentName() != "" ) ? ucwords(strtolower($userVO->getParentName())) : '' ?></p>
                        -->
                        
                        <p style="margin-bottom: 0px !important; font-size: 7pt !important; font-style: italic;"><?php echo ($bloodDonationVO['FatherName'] != null && $bloodDonationVO['FatherName'] != "" ) ? "Mr. " . ucwords(strtolower($bloodDonationVO['FatherName'])) : '' ?></p>
                        <p style="margin-bottom: 0px !important; font-size: 7pt !important; font-style: italic;">
                        	<?php echo ($bloodDonationVO['MobileNumber1'] != null && $bloodDonationVO['MobileNumber1'] != "" ) ? ($bloodDonationVO['MobileNumber1'] != '9999999999' ? '<i class="fa fa-phone"></i> ' . $bloodDonationVO['MobileNumber1'] : '' )  : '' ?>
                        </p>
                        
                        <?php $address = (strpos($bloodDonationVO['Area'], $bloodDonationVO['Address']) == false) ? $bloodDonationVO['Address'] . ", " : "" ?>
                        <p style="margin-bottom: 0px !important; font-size: 7pt !important; font-style: italic;"><?php echo ($bloodDonationVO['Area'] != null && $bloodDonationVO['Area'] != "") ? '<i class="fa fa-home"></i> ' . $address . $bloodDonationVO['Area'] . ', ' . $bloodDonationVO['CityName'] : '' ?></p>
                    </div>
                    
                    
                    <div class="m-1 rounded text-center" style="width:50px;">
                 	<p>
                	 <a href="tel:<?php echo $bloodDonationVO['MobileNumber1']; ?>">
                          <i class="fa fa-phone" style="font-size:48px;color:green"></i>
                     </a>
                 </p>
                	</div>
                    
            		
               </div>
            	

				 
               	
           		<div class="media">
        			   		     
                    <div class="text-left">
                    	<p class="small" style="font-size: 7pt !important; font-style: italic;"></p>
                    </div>
                    
                    <div class="media-body text-center">
                    		<?php if($bloodDonationVO['IsStpEligible']): ?>
                    			<p class="small font-italic" style="margin-bottom: 0px !important; font-size:16px;color:green; " ><?php echo "SDP Eligible"; ?></p>
                    		<?php endif; ?>
                    </div>
                    
                	<div class="text-right" >
            		    <p class="small font-italic" style="margin-bottom: 0px !important; font-size:16px;color:red; " ><?php  echo "" . $bloodDonationVO['BloodGroup'];  ?></p>
                  	</div>
            
            	</div>	
				
				
				
				 	
            	
            	 
        	</li>
    	<?php endforeach; ?>
    	</ul>
    	
    	
    <?php else: ?> 	
    	
    	<div class="media">
        			   		     
            <div class="text-left">
            	<p class="small" style="font-size: 7pt !important; font-style: italic;"></p>
            </div>
            
            <div class="media-body text-center">
            	<p class="small font-italic" style="margin-bottom: 0px !important; font-size:16px; " ><?php echo "Oops! Donor Not Found."; ?></p>
            </div>
            
        	<div class="text-right" >
    		    <p class="small font-italic" style="margin-bottom: 0px !important; font-size:16px;color:red; " ></p>
          	</div>
    
    	</div>	
    	
    <?php endif; ?>
    </div>
</div>





<script>
$(document).ready(function(){
  $("#Search").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#DonorList li").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
