<?php
$donationVOs = $this->getDonationVOs();
$total = sizeof($donationVOs);
?>

<div class="card bg-light text-dark" style="margin: 50px 0px 10px 0px !important;">
	<div class="card-body" style="padding:0px !important;">
		<table class="table" style="margin-bottom: 0px !important;">
			<tbody>
				<tr>
					<td style="border-top:none; width: 20% !important;" class="text-left">
						<span style="font-weight:bold;"><?php // echo $total; ?></span>
					</td>
					
					<td style="border-top:none; vertical-align: middle;" class="text-center">
						<span style="font-weight:bold;">
							Donor List
						</span>
					</td>
					
					<td style="border-top:none; width: 20% !important;" class="text-left">
						<input class="form-control" id="Search" type="text" placeholder="Search..">
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

<div class="card bg-light">
    <div class="card-body" id="DonorContainer" >
    
    <?php if($total > 0):?>
    
    
        <?php $counter = 0; ?>
        <?php /* @var $donationVO Margshri_Common_VO_Donation_Donation_DonationVO */ ?>
        
        <ul class="list-group" id="DonorList">
        <?php foreach($donationVOs as $donationVO): ?>
        
        	<?php /* @var $userVO Margshri_Common_VO_User_User_UserVO */ ?>
        	<?php $userVO = $donationVO->getUserVO(); ?>
        
        	<?php /* @var $donationTypeVO Margshri_Common_VO_Donation_DonationType_DonationTypeVO */ ?>
        	<?php $donationTypeVO = $donationVO->getDonationTypeVO(); ?>
        	
        
        	<?php $counter++;?>
        	
        	<li class="list-group-item">
        	
            	<div class="media  p-3" style="padding:.5rem !important;">
                <?php if($userVO->getUserImageURL() != null && $userVO->getUserImageURL() != "" && file_exists(Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $userVO->getUserImageURL()) ): ?>
                     <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $userVO->getUserImageURL() ?>" alt="donor" class="mr-3 mt-3 rounded-circle text-left" style="width:60px; margin-top: 0px !important;">
                <?php else: ?>
                     <div class="mr-3 mt-3 rounded-circle text-left" style="width:30px; margin-top: 0px !important;"></div>
                <?php endif; ?>
            
                    <div class="media-body text-center">
                        <p style="margin-bottom: 0px !important;" ><small><b><?php echo ($userVO->getName() != null && $userVO->getName() != "") ?  ucwords(strtolower($userVO->getName())) : '' ?></b></small></p>
                        <p style="margin-bottom: 0px !important; font-size: 7pt !important; font-style: italic;"><?php echo ($userVO->getFatherName() != null && $userVO->getFatherName() != "" ) ? 'S/O Mr. ' . ucwords(strtolower($userVO->getFatherName())) : '' ?></p>
                        
                
                        
                        <p style="margin-bottom: 0px !important; font-size: 7pt !important; font-style: italic;">
                        	<?php echo ($userVO->getMobileNumber1() != null && $userVO->getMobileNumber1() != "" ) ? $userVO->getMobileNumber1() : '' ?>
                        </p>
                        
                        <p style="margin-bottom: 0px !important; font-size: 7pt !important; font-style: italic;"><?php echo ($userVO->getMobileNumber1() != null && $userVO->getAddress() != "" ) ? $userVO->getAddress() : '' ?></p>
                        
                    </div>
            
            		  
            		<div class="text-right" style="width:60px; margin-top: 0px !important; ">
            		    <?php if($donationTypeVO->getTypeImage() != null && $donationTypeVO->getTypeImage() != "" ): ?>
                             <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $donationTypeVO->getTypeImage() ?>" alt="donationtype" class="mr-3 mt-3 rounded-circle text-left" style="width:60px; height:60px; margin-top: 0px !important;">
                        <?php endif; ?>
                  	</div>
            	  </div>
        	</li>
    	<?php endforeach; ?>
    	</ul>
    <?php endif; ?>
    </div>
</div>

<script>
$(document).ready(function(){
  $("#Search").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#DonorList li").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>