<?php 
$useIas = Mage::getStoreConfigFlag('iscroll/general/useajaxscroll');
if ($useIas) {
	
	$productListMode = Mage::getStoreConfig('catalog/frontend/list_mode');
	if ($productListMode == 'grid-list')
		$productListMode = 'grid';
	elseif ($productListMode == 'list-grid')
		$productListMode = 'list';

	
	if ($this->getRequest()->getParam('mode')) {
		if($this->getRequest()->getParam('mode') == 'grid')
			$productListMode = 'grid';
		else
			$productListMode = 'list';
	}
}
?>
<?php if ($useIas): ?>
<script type="text/javascript">
jQuery.iscroll({
	container : '.category-products',
	<?php if ($productListMode == 'grid'): ?>
	item: '.products-grid',
	<?php else: ?>
	item: '.products-list',
	<?php endif; ?>
	pagination: '.toolbar .pager',
	next: '.next',
	loader: '<img src="<?php echo($this->getSkinUrl('images/opc-ajax-loader.gif')); ?>" /> <?php echo __('Loading more products...'); ?>'
});
</script>
<?php endif; ?>
