<?php
/* @var $systemConfigVO Dakiya_VO_Master_System_SystemConfig_SystemConfigVO */ 
$systemConfigVO = $this->getSystemConfigVO();
if($systemConfigVO == null){
	$systemConfigVO = new Dakiya_VO_Master_System_SystemConfig_SystemConfigVO();
}
?>

<div class="entry-edit">

	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">System Config</h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset ">
		<div class="hor-scroll">
			
			<table class="form-list">
				<tbody>
				
					<tr>
						<td class="label">
							<label for="ConfigName">Config Name<span class="required">*</span></label>
						</td>
						<td class="value">
							<input id="ConfigName" name="ConfigName" value="<?php echo $systemConfigVO->getConfigName() ?>" 
							class="required-entry input-text" type="text" />
						</td>
					</tr>
				
					<tr>
						<td class="label">
							<label for="ConfigKey">Config Key<span class="required">*</span></label>
						</td>
						<td class="value">
							<input id="ConfigKey" name="ConfigKey" value="<?php echo $systemConfigVO->getConfigKey() ?>" 
							class="required-entry input-text" type="text" <?php echo ($systemConfigVO->getConfigID() != null ) ? 'readonly= "readonly" ' : '' ?> />
						</td>
					</tr>
				
					<tr>
						<td class="label">
							<label for="ConfigValue">Config Value<span class="required">*</span></label>
						</td>
						<td class="value">
							<input id="ConfigValue" name="ConfigValue" value="<?php echo $systemConfigVO->getConfigValue() ?>" 
							class="required-entry input-text" type="text" />
							<input id="ConfigID" name="ConfigID" value="<?php echo ($systemConfigVO->getConfigID() != null ) ? $systemConfigVO->getConfigID() : 0 ?>" type="hidden" />
						</td>
					</tr>
					
					 
					
				</tbody>
			</table>
						 
		</div>
	</div>

</div>