<?php ?>
<div class="card bg-light text-dark" style="margin-bottom: 10px !important;">
	<div class="card-body" style="padding:0px !important;">
		<table class="table" style="margin-bottom: 0px !important;">
			<tbody>
				<tr>
					<!--  
					<td style="border-top:none; width: 20% !important;" class="text-left"></td>
					-->
					
					<td style="border-top:none; vertical-align: middle; " class="text-center">
						  <p>Develop and maintain by margshri.com</p>
                          <p>For Technical Support Please Contact</p>
                          <p>Vipin Shakya 9887317538</p>
					</td>
					
					<!--    
					<td style="border-top:none; width: 20% !important;" class="text-left"></td>
					-->
				</tr>
			</tbody>
		</table>
	</div>
</div>