<?php ?>
<style>
<!--
.requiredField:after {content:"*";color:red;}  
-->
</style>

<div class="card bg-light text-dark" style="margin-top: 50px !important; margin-bottom: 10px !important;">
	<div class="card-body" style="padding:0px !important;">
		<table class="table" style="margin-bottom: 0px !important;">
			<tbody>
				<tr>
					<td style="border-top:none; width: 20% !important;" class="text-left">
						<img class="rounded-circle" width="100px" height="100px" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/default/default/images/buddhaG.png'  ?>" alt="buddhaG image"  onclick="return baseFormJS.redirect('<?php echo $this->getUrl("medicalcamp/Registration_Registration/index") ?>')" />
					</td>
					
					<td style="border-top:none; vertical-align: middle; " class="text-center">
						<h5>शाक्य महासभा समिति श्री गंगानगर</h5>
  						<p>प्रतिभा सम्मान समारोह</p>
  						<!--  
  						<p>29 दिसंबर 2019</p>
  						-->
  					</td>
					<!--  
					<td style="border-top:none; width: 20% !important;" class="text-left"></td>
					-->
				</tr>
			</tbody>
		</table>
	</div>
</div>

