<?php
$registrationVO = $this->getRegistrationVO();
if($registrationVO == null){
    $registrationVO = new Margshri_MedicalCamp_VO_RegistrationVO();
}
$HTMLFormID = $this->getHTMLFormID();
?>

<script type="text/javascript">

var registrationDataStr = '<?php echo (sizeof($registrationVO->getBaseDataArray()) > 0) ? json_encode($registrationVO->getBaseDataArray()) : "" ?>';
var registrationDataObj = null;
if(registrationDataStr != ''){
	registrationDataObj = JSON.parse(registrationDataStr); 		
}
</script>

<?php echo $this->getHeaderHtml() ?>

<div class="card bg-light text-dark" style="margin-bottom: 10px !important;">
	<div class="card-body" style="padding:0px !important;">
		<table class="table" style="margin-bottom: 0px !important;">
			<tbody>
				<tr>
					<td style="border-top:none; width: 20% !important;" class="text-left"></td>
					<td style="border-top:none; vertical-align: middle; " class="text-center">
						<span style="font-weight:bold;">Home</span>
					</td>
					<td style="border-top:none; width: 20% !important;" class="text-left">
						<div class="col-xs-9 col-xs-offset-3">
                            <button type="button" class="btn btn-info" onclick="return baseFormJS.redirect('<?php echo $this->getUrl("medicalcamp/Registration_Registration/showGenius") ?>')" >Genius List</button>
                        </div>
                    </td>
				</tr>
			</tbody>
		</table>
	</div>
</div>


  
<form action="<?php echo $this->getUrl('medicalcamp/Registration_Registration/edit') ?>" method="post" id="<?php echo $HTMLFormID ?>" enctype="multipart/form-data" >
	<?php echo $this->getBlockHtml('formkey')?>
	
    <div class="container">
      <div class="row">
        
        <div class="col-sm-6">
             <div class="form-group">
                <div class="card">
                	<div class="card-header">New Registration</div>
                    <div class="card-body">
                    	<div class="col-xs-9 col-xs-offset-3">
                            <button type="button" class="btn btn-info" id="NewRegistrationBtn" name="NewRegistrationBtn" value="New Registration" onclick="return baseFormJS.redirect('<?php echo $this->getUrl("medicalcamp/Registration_Registration/showNewForm") ?>')" >New Registration</button>
                        </div>
                    </div>
                </div>
			</div>
        </div>
        
        <div class="col-sm-6">
        	<div class="form-group">
              	<div class="card">
                	<div class="card-header">Edit Form</div>
                    <div class="card-body">
                    	<div class="form-group">          
                            <label for="TransactionID" class="requiredField">Registration Number</label>
                            <input type="text" class="form-control" name="TransactionID" id="TransactionID" pattern="[0-9]*" inputmode="numeric" value="<?php echo $registrationVO->getTransactionID() ?>" />
                        </div>
                        
                        
                        <div class="form-group">          
                            <label for="MobileNumber" class="requiredField">Mobile Number</label>
                            <input type="text" class="form-control" name="MobileNumber" id="MobileNumber" maxlength="10" pattern="[0-9]*" inputmode="numeric" value="<?php echo $registrationVO->getMobileNumber() ?>" placeholder="10 digit only (without +91 or 0)" />
                        </div>
                        
                    </div>
                    <div class="card-footer">
                		<div class="col-xs-9 col-xs-offset-3">
                            <button type="button" class="btn btn-info" id="EditFormBtn" name="EditFormBtn" value="Submit" onclick="return homeFormJS.submit()" >Submit</button>
                        </div>    
                    </div>
                </div>
            </div>
        </div>
         
      </div>
    </div>
</form>

<?php echo $this->getFooterHtml() ?>

<script type="text/javascript">
//<![CDATA[

    var homeFormJS = {
    		
    		submit : function(){
        		if(!homeFormJS.submitValidation()){
            		return false;
        		}
				$("#overlay").css("display","block");
    			$("#loader").css("display","block");
    			$('#<?php echo $HTMLFormID ?>').submit();
    		},

    		submitValidation : function(){
    			var transactionID = $.trim($('#TransactionID').val());
    			var mobileNumber = $.trim($('#MobileNumber').val());
    			
    			if(transactionID == null || transactionID == ""){
    				$('#AlertBoxModal').modal('show');
    				$('#AlertBoxModalBody').html("Please Enter Registration Number.");
    				$('#AlertBoxModal').on('hidden.bs.modal', function () {
    					$('#TransactionID').focus();
    				});
    				return false;
    			}


    			if(mobileNumber == null || mobileNumber == ""){
    				$('#AlertBoxModal').modal('show');
    				$('#AlertBoxModalBody').html("Please Enter Mobile Number.");
    				$('#AlertBoxModal').on('hidden.bs.modal', function () {
    					$('#MobileNumber').focus();
    				});
    				return false;
    			}

    			if(!Validate.isMobileNOValid(mobileNumber)){
    				$('#AlertBoxModal').modal('show');
    				$('#AlertBoxModalBody').html('Please Enter Valid Mobile Number.');
    				$('#AlertBoxModal').on('hidden.bs.modal', function () {
    					$('#MobileNumber').val("");
    			    	$('#MobileNumber').focus();
    				});
    				return false;
    			}

    			
    	    	return true;
    		},

    		defaultSetting: function(){
    			if(registrationDataObj != null && registrationDataObj != ""){
        			$('#AlertBoxModal').modal('show');
    				$('#AlertBoxModalBody').html(registrationDataObj.ErrorMessage);
    				$('#AlertBoxModal').on('hidden.bs.modal', function () {});
    			}

    			if (window.history && window.history.pushState) {
    			    window.history.pushState('forward', null, './#forward');
    			    $(window).on('popstate', function() {
    			    	window.location.href = "#";    
    			    });
    			}
    		} 
    };
    homeFormJS.defaultSetting();
//]]>
</script>