<?php
$registrationVO = $this->getRegistrationVO();
if($registrationVO == null){
	$registrationVO = new Margshri_MedicalCamp_VO_RegistrationVO();
}
$HTMLFormID = $this->getHTMLFormID();
?>
<!--
<link rel="stylesheet" type="text/css" href="http://localhost/apct/js/calendar/calendar-win2k-1.css" />
<script type="text/javascript" src="http://localhost/apct/js/calendar/calendar.js"></script>
<script type="text/javascript" src="http://localhost/apct/js/calendar/calendar-setup.js"></script>

<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.1.3/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
-->

<!--
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script type="text/javascript" src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.min.js"></script>
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.1.3/js/bootstrap-datetimepicker.min.js"></script>
-->


<script type="text/javascript">
//<![CDATA[
enUS = {"m":{"wide":["January","February","March","April","May","June","July","August","September","October","November","December"],"abbr":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]}}; // en_US locale reference
Calendar._DN = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]; // full day names
Calendar._SDN = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]; // short day names
Calendar._FD = 0; // First day of the week. "0" means display Sunday first, "1" means display Monday first, etc.
Calendar._MN = ["January","February","March","April","May","June","July","August","September","October","November","December"]; // full month names
Calendar._SMN = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]; // short month names
Calendar._am = "AM"; // am/pm
Calendar._pm = "PM";

// tooltips
Calendar._TT = {};
Calendar._TT["INFO"] = "About the calendar";

Calendar._TT["ABOUT"] =
"DHTML Date/Time Selector\n" +
"(c) dynarch.com 2002-2005 / Author: Mihai Bazon\n" +
"For latest version visit: http://www.dynarch.com/projects/calendar/\n" +
"Distributed under GNU LGPL. See http://gnu.org/licenses/lgpl.html for details." +
"\n\n" +
"Date selection:\n" +
"- Use the \xab, \xbb buttons to select year\n" +
"- Use the " + String.fromCharCode(0x2039) + ", " + String.fromCharCode(0x203a) + " buttons to select month\n" +
"- Hold mouse button on any of the above buttons for faster selection.";
Calendar._TT["ABOUT_TIME"] = "\n\n" +
"Time selection:\n" +
"- Click on any of the time parts to increase it\n" +
"- or Shift-click to decrease it\n" +
"- or click and drag for faster selection.";

Calendar._TT["PREV_YEAR"] = "Prev. year (hold for menu)";
Calendar._TT["PREV_MONTH"] = "Prev. month (hold for menu)";
Calendar._TT["GO_TODAY"] = "Go Today";
Calendar._TT["NEXT_MONTH"] = "Next month (hold for menu)";
Calendar._TT["NEXT_YEAR"] = "Next year (hold for menu)";
Calendar._TT["SEL_DATE"] = "Select date";
Calendar._TT["DRAG_TO_MOVE"] = "Drag to move";
Calendar._TT["PART_TODAY"] = ' (' + "Today" + ')';

// the following is to inform that "%s" is to be the first day of week
Calendar._TT["DAY_FIRST"] = "Display %s first";

// This may be locale-dependent. It specifies the week-end days, as an array
// of comma-separated numbers. The numbers are from 0 to 6: 0 means Sunday, 1
// means Monday, etc.
Calendar._TT["WEEKEND"] = "0,6";

Calendar._TT["CLOSE"] = "Close";
Calendar._TT["TODAY"] = "Today";
Calendar._TT["TIME_PART"] = "(Shift-)Click or drag to change value";

// date formats
Calendar._TT["DEF_DATE_FORMAT"] = "%b %e, %Y";
Calendar._TT["TT_DATE_FORMAT"] = "%B %e, %Y";

Calendar._TT["WK"] = "Week";
Calendar._TT["TIME"] = "Time:";

CalendarDateObject._LOCAL_TIMZEONE_OFFSET_SECONDS = 19800;
CalendarDateObject._SERVER_TIMZEONE_SECONDS = 1501254359;

//]]>
</script>



<script type="text/javascript">

var registrationDataStr = '<?php echo (sizeof($registrationVO->getBaseDataArray()) > 0) ? json_encode($registrationVO->getBaseDataArray()) : "" ?>';
var registrationDataObj = null;
if(registrationDataStr != ''){
	registrationDataObj = JSON.parse(registrationDataStr); 		
}

</script>

<div class="block block-list block-categories" >
    <div id="block-categories" class="block-center-title active">
        <strong><span id="CustomPageTitle">Registration Form</span></strong>
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p> 
    </div>
</div>

</form>

  <!--  	
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  
  
  <script>
  
  $( function() {
    $( "#DOB" ).datepicker();
  } );
  
  </script>
  -->

<div style="text-align: center; margin-bottom: 10px !important;">
	<a href="<?php echo Mage::getUrl('medicalcamp/Registration_Registration/index') ?>"> 
		<img alt="middleImage" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'web_portal/frontend/advertisement/middle/ChamberOfCommerce/img_2.jpg' ?>" width="592px" height="150px">
	</a>
</div>

<div style="margin-bottom: 10px !important; width: 500px !important;">
	<div style="text-align: center; width: 200px !important; float: left !important;">
		<a  href="#" onclick = "return studentFormJS.aboutScholarship()">About Scholarship</a> 
	</div>
	
	<div style="text-align: center; width: 100px !important; float: left !important;">
		<a  href="<?php echo $this->getUrl("medicalcamp/Registration_Registration/admitCardFilter") ?>" >Download Admit Card</a> 
	</div>
	
	<div style="text-align: center; width: 200px !important; float: right !important;">
		<a style="text-align: center; width: 45% !important;" href="#" onclick = "return studentFormJS.syllabusExam()">Syllabus and Exam pattern</a>
	</div>	
</div>

<!--  
<div id="ErrorMessageDiv" style="display: none;">
	<ul class="messages"><li class="error-msg"><ul><li><span id="ErrorMessage"></span></li></ul></li></ul>
</div>
-->

<form action="<?php echo $this->getUrl('medicalcamp/Registration_Registration/save') ?>" method="post" id="<?php echo $HTMLFormID ?>" enctype="multipart/form-data" >
	
	<div class="fieldset" style="margin-bottom: 0px !important;">
        <?php echo $this->getBlockHtml('formkey')?>
        
        <table>
        	<tr>
        		<td>
			        <ul class="form-list">
			            <li>
			                <label for="FirstName" class="required"><em>*</em>First Name</label>
			                <div class="input-box">
			                      <input name="FirstName" id="FirstName" class="input-text required-entry" type="text" value="<?php echo $registrationVO->getFirstName() ?>" />
			                </div>
			            </li>
			            
			            <li>
			                <label for="LastName">Last Name</label>
			                <div class="input-box">
			                      <input name="LastName" id="LastName" class="input-text required-entry" type="text" value="<?php echo $registrationVO->getLastName() ?>" />
			                </div>
			            </li>
			            
			            <li>
			                <label for="FatherName" class="required"><em>*</em>Father Name</label>
			                <div class="input-box">
			                      <input name="FatherName" id="FatherName" class="input-text required-entry" type="text" value="<?php echo $registrationVO->getFatherName() ?>"  />
			                </div>
			            </li>
			            
			            <li>
			                <label for="DOB" class="required"><em>*</em>Date Of Birth</label>
			                <div class="input-box">
			                      <input name="DOB" id="DOB" class="input-text required-entry" type="text" value="<?php echo $registrationVO->getDOB() ?>" style ="width: 235px !important;" />
			               

							<img src="<?php  echo Mage::getDesign()->getSkinUrl('images/grid-cal.gif') ?>"
							alt="" class="v-middle" id="DOBIMG" title="Select Date" style="">
							
							<script type="text/javascript">
	                                 //<![CDATA[
	                                 Calendar.setup({
                                          inputField: "DOB",
                                          ifFormat: "%Y-%m-%d",
                                          //showsTime: 12,
                                          button: "DOBIMG",
                                          align: "Bl",
                                          singleClick : true
	                                 });
	                                 //]]>
	                        </script>
 							</div>
			            </li>

 


			            
			            <li>
			            	<label for="Gender" class="required"><em>*</em>Gender</label>
			                <div class="input-box">
			                	  <select name="Gender" id="Gender" class="validate-select" >
			                		<option value="" >--Select--</option>
			                		<?php foreach ($this->getGenderListOptions() as $key=>$value): ?>
				                		<option value="<?php echo $key ?>" <?php echo ($key==$registrationVO->getGender()) ? "selected='selected'" : "" ?>><?php echo $value ?></option>
				                	<?php endforeach; ?>	  
			                	  </select>
			                </div>
			            </li>
			            
			            <li>
			            	<label for="MobileNumber" class="required"><em>*</em>Mobile Number</label>
			                <div class="input-box">
			                      <input name="MobileNumber" id="MobileNumber" class="input-text required-entry validate-digits" type="text" maxlength="10" value="<?php echo $registrationVO->getMobileNumber()  ?>" />
			                      <span>10 digit only (without +91 or 0)</span>
			                </div>
			            </li>
			            
			            
			            <li>
			                <label for="Email" class="required"><em>*</em>Email</label>
			                <div class="input-box">
			                      <input name="Email" id="Email" class="input-text required-entry validate-email" type="text" value="<?php echo $registrationVO->getEmail()  ?>" />
			                </div>
			            </li>
			            
			            <li>
			            	<label for="CurrentSchool" class="required"><em>*</em>Current School</label>
			                <div class="input-box">
								<input name="CurrentSchool" id="CurrentSchool" class="input-text required-entry " type="text" value="<?php echo $registrationVO->getCurrentSchool()  ?>" />



								  <!--
			                	  <select name="CurrentSchool"  id="CurrentSchool" class="validate-select" >
			                	  	<option value="">--Select--</option>
			                	  	<?php //foreach ($this->getSchoolOptions() as $key=>$value): ?>
			                	  	<option value="<?php //echo $key?>" <?php //echo ($key==$registrationVO->getCurrentSchool()) ?  "selected='selected'" : "" ?>><?php //echo $value?></option>
			                	  	<?php //endforeach; ?>
			                	  </select>	
								  -->	

			                </div>
			            </li>

						<li>
			            	<label for="ClassID" class="required"><em>*</em>Class</label>
			                <div class="input-box">
			                	  <select name="ClassID"  id="ClassID" class="validate-select" >
			                	  	<option value="">--Select--</option>
			                	  	<?php foreach ($this->getClassOptions() as $key=>$value): ?>
			                	  	<option value="<?php echo $key?>" <?php echo ($key==$registrationVO->getClassID()) ?  "selected='selected'" : "" ?>><?php echo $value?></option>
			                	  	<?php endforeach; ?>
			                	  </select>	
			                </div>
			            </li>


						<li>
			            	<label for="SubjectID" class="required"><em>*</em>Subject</label>
			                <div class="input-box">
			                	  <select name="SubjectID"  id="SubjectID" class="validate-select" >
			                	  	<option value="">--Select--</option>
			                	  	<?php foreach ($this->getSubjectOptions() as $key=>$value): ?>
			                	  	<option value="<?php echo $key?>" <?php echo ($key==$registrationVO->getSubjectID()) ?  "selected='selected'" : "" ?>><?php echo $value?></option>
			                	  	<?php endforeach; ?>
			                	  </select>	
			                </div>
			            </li>


						<li>
			            	<label for="BoardID" class="required"><em>*</em>Board</label>
			                <div class="input-box">
			                	  <select name="BoardID"  id="BoardID" class="validate-select" >
			                	  	<option value="">--Select--</option>
			                	  	<?php foreach ($this->getBoardOptions() as $key=>$value): ?>
			                	  	<option value="<?php echo $key?>" <?php echo ($key==$registrationVO->getBoardID()) ?  "selected='selected'" : "" ?>><?php echo $value?></option>
			                	  	<?php endforeach; ?>
			                	  </select>	
			                </div>
			            </li>

			            
			            
			           			     
			            <li>
			                <input name="TermsAndCondition" id="TermsAndCondition" type="checkbox" value=""> 
			                &nbsp;&nbsp;&nbsp;&nbsp;<span>Accept All <a href="<?php echo $this->getUrl('medicalcamp/Registration_Registration/terms') ?>" target="_blank">Terms And Condition</a></span>
			            </li>
			        </ul>
			     </td>
			     
			     <td style="width: 100px !important;"></td>
			     
			     <td>
			     
			     	<ul class="form-list">
			            
			            <li>
			                <label for="StudentImgURL" class="required"><em>*</em>Student Image</label><br />
            				<table>
            					<tr>
            						<td>
		            				 	<div style="border: 1px solid; border-color: #AAA #C8C8C8 #C8C8C8 #AAA;" class="customer-image">
											<img id="StudentImgPreview" alt="" src=""  style="border-style: hidden;" class="customer-image" />
											<input type="file" id="StudentImgFile" name="StudentImgFile" onchange="return studentFormJS.getStudentImgPath()" style="display: none;" />
										</div>		
		                			</td>
            					</tr>
            					
            					<tr style="height: 5px;"></tr>
            					
            					<tr>
            						<td style="text-align: center;">
            							<button type="button" class="button" id="StudentImgBrowse" name="StudentImgBrowse" onclick="return studentFormJS.browseStudentImgFile()" >
            								<span>
            									<span>Browse</span>	
            								</span>
            							</button>


										<input type="hidden" id="ID" name="ID" value="0" />
            							<input type="hidden" id="StudentImgURL" name="StudentImgURL" value="" />
            						</td>
            					</tr>	
            				</table>	
            			</li>
            			

						<li>
			            	<label for="Address" class="required"><em>*</em>Address</label>
			                <div class="input-box">
			                	<textarea rows="2" cols="20" name="Address" id="Address" class="input-text required-entry" style="width: 252px !important; height: 50px;" ><?php echo $registrationVO->getAddress()  ?></textarea>
			                </div>
			            </li>



						<li>
			            	<label for="CountryID">Country</label>
			                <div class="input-box">
			                	 <select name="CountryID" id="CountryID" disabled="disabled">
									<option value="1" selected="selected">India</option>	
								 </select>
			                </div>
			            </li>

						<li>
			            	<label for="StateID">State</label>
			                <div class="input-box">
			                	 <select name="StateID" id="StateID" disabled="disabled">
									<option value="29" selected="selected">Rajasthan</option>	
								 </select>
			                </div>
			            </li>

						<li>
			            	<label for="DistrictID">District</label>
			                <div class="input-box">
			                	 <select name="DistrictID" id="DistrictID" disabled="disabled">
									<option value="31" selected="selected">Sri Ganganagar</option>	
								 </select>
			                </div>
			            </li>

						<li>
			            	<label for="CityID">City</label>
			                <div class="input-box">
			                	<select name="CityID" id="CityID" class="validate-select" >
					        		<option value="" >--Select--</option>
					        		<?php foreach ($this->getCityOptions() as $key=>$value): ?>
						        		<option value="<?php echo $key ?>" <?php echo ($key == $registrationVO->getCityID()) ? "selected='selected'" : "" ?>><?php echo $value ?></option>
						        	<?php endforeach; ?>	  
							    </select>
			                </div>
			            </li>

						<li>
			            	<label for="AddharCardNumber"  class="required"><em>*</em>Aadhaar Card Number</label>
			                <div class="input-box">
			                	  <input name="AddharCardNumber" id="AddharCardNumber" class="input-text required-entry validate-digits" type="text" maxlength="12" value="<?php echo $registrationVO->getAddharCardNumber()  ?>" >
			                </div>
			            </li>

						<!--
            			<li>
			                <label for="AddharCardURL" class="required"><em>*</em>Addhar Card Image</label><br />
            				<table>
            					<tr>
            						<td>
		            				 	<div style="border: 1px solid; border-color: #AAA #C8C8C8 #C8C8C8 #AAA;" class="customer-image">
											<img id="AddharCardPreview" alt="" src=""  style="border-style: hidden;" class="customer-image" />
											<input type="file" id="AddharCardFile" name="AddharCardFile" onchange="return studentFormJS.getAddharCardFilePath()" style="display: none;" />
										</div>		
		                			</td>
            					</tr>    		
            					
            					
            					<tr style="height: 5px;"></tr>
            					
            					<tr>
            						<td style="text-align: center;">
            							<button type="button" class="button" id="AddharCardBrowse" name="AddharCardBrowse" onclick="return studentFormJS.browseAddharCardFile()" >
            								<span>
            									<span>Browse</span>	
            								</span>
            							</button>
            							<input type="hidden" id="AddharCardURL" name="AddharCardURL" value="" />
            						</td>
            					</tr>	
            				</table>	
            			</li>
						-->            			


            		</ul>		
            	</td>
              </tr>   
        
       </table>
    </div> 	
	
	<div class="buttons-set" style="margin-top: 0px !important; border-top: none !important; border-bottom: 1px solid #E4E4E4 !important; ">
    	<button type="button" title="<?php echo $this->__('Save') ?>" id="StudentRegistrationButton" name="StudentRegistrationButton" class="button" onclick="return studentFormJS.submit() "><span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>
    
</form>

<form>

 

<script type="text/javascript">
//<![CDATA[
           
    var studentFormObj= new VarienForm('<?php echo $HTMLFormID ?>', true);

    var studentFormJS = {

    		browseStudentImgFile: function(){
    			$('StudentImgFile').click();
    		},

    		getStudentImgPath: function(){
    		    var studentImgURL = $("StudentImgFile").files[0];
    		    $("StudentImgPreview").src = window.URL.createObjectURL(studentImgURL);
    		},

    		browseAddharCardFile: function(){
    			$('AddharCardFile').click();
    		},

    		getAddharCardFilePath: function(){
    		    var aadhaarCardURL = $("AddharCardFile").files[0];
    		    $("AddharCardPreview").src = window.URL.createObjectURL(aadhaarCardURL);
    		},
    		
    		submit : function(){
        		if(!studentFormJS.saveValidation()){
            		return ;
        		}	 
        		$('<?php echo $HTMLFormID ?>').submit();
    		},

    		saveValidation : function(){
    			
    			if(!(studentFormObj.validator && studentFormObj.validator.validate())){
        	    	return false;
    	    	}
				
						             	
				if($('StudentImgFile').value == null || $('StudentImgFile').value == ''){
					alert('Please Select Student Image !');
					return false;
				}

				/*
				if($('AddharCardFile').value == null || $('AddharCardFile').value == ''){
					alert('Please Select Addhar Card Image !');
					return false;
				}
				*/	

				if(!$('TermsAndCondition').checked){
	             	alert('Please Accept Term And Conditions !');
	             	return false;
				}
				
    	    	return true;
    		},

    		syllabusExam : function(){
    			var syllabusExamHTML = '';
    			syllabusExamHTML  = '<div class="fieldset"><div class="grid tier" style="width:90%;">';
    			syllabusExamHTML += '<table cellspacing="0" width = "100%" style="margin:2% 2% 2% 2% !important;">';
    			syllabusExamHTML += '<tr>';
    			syllabusExamHTML += '<th><img src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'web_portal/frontend/advertisement/middle/ChamberOfCommerce/img_3.jpg' ?>" style="width:850px !important; height:630px !important;"	alt="popupad" /></th>';
    			syllabusExamHTML += '</tr>';
    			syllabusExamHTML += '</table></div>';
    			
    			$j(document).ready(function(){
    			   $j.colorbox({ width:"10%", height:"10%" ,fastIframe:false ,fixed:true, html:true ,html:syllabusExamHTML , overlayClose:false,
    				   onLoad: function() { $j('#cboxClose').hide(); },
    				   onComplete :function() { $j('#cboxClose').show(); $j.colorbox.resize({width:'900px',height:'720px'});},
    				   onClosed:function(){ }
    				});
    			});
        	},
    		
    		aboutScholarship : function(){
    			var aboutScholarshipHTML = '';
    			aboutScholarshipHTML  = '<div class="fieldset"><div class="grid tier" style="width:90%;">';
    			aboutScholarshipHTML += '<table cellspacing="0" width = "100%" style="margin:2% 2% 2% 2% !important;">';
    			aboutScholarshipHTML += '<tr>';
    			aboutScholarshipHTML += '<th><img src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'web_portal/frontend/advertisement/middle/ChamberOfCommerce/img_4.jpg' ?>" style="width:690px !important; height:790px !important;"	alt="popupad" /></th>';
    			aboutScholarshipHTML += '</tr>';
    			aboutScholarshipHTML += '</table></div>';
    			
    			$j(document).ready(function(){
    			   $j.colorbox({ width:"10%", height:"10%" ,fastIframe:false ,fixed:true, html:true ,html:aboutScholarshipHTML , overlayClose:false,
    				   onLoad: function() { $j('#cboxClose').hide(); },
    				   onComplete :function() { $j('#cboxClose').show(); $j.colorbox.resize({width:'750px',height:'800px'});},
    				   onClosed:function(){ }
    				});
    			 });
    							
        	}

    		
    };
	//alert(registrationDataObj.ErrorMessage);
	
	if(registrationDataObj != ''){
		$('ErrorMessageDiv').style.display = "block";
		$('ErrorMessage').innerHTML = registrationDataObj.ErrorMessage;
	}
    	
//]]>
</script>
