<?php
$currentPaymentPost = $this->getCurrentPaymentPost();
$HTMLFormID = $this->getHTMLFormID();
?>




<div class="block block-list block-categories" >
    <div id="block-categories" class="block-center-title active">
        <strong><span id="CustomPageTitle">Paymet Page</span></strong>
    </div>
</div>

</form>

<div style="text-align: center; margin-bottom: 10px !important;">
	<a href="<?php echo Mage::getUrl('medicalcamp/Registration_Registration/index') ?>"> 
		<img alt="middleImage" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'web_portal/frontend/advertisement/middle/ChamberOfCommerce/img_2.jpg' ?>" width="592px" height="150px">
	</a>
</div>

<form action="<?php echo $currentPaymentPost['action'] ?>" method="post" id="<?php echo $HTMLFormID ?>" enctype="multipart/form-data" >
	
	<div class="fieldset" style="margin-bottom: 0px !important;">
        <?php echo $this->getBlockHtml('formkey')?>
        
        <table>
        	<tr>
        		<td>
			        <ul class="form-list">
			            <li>
			                <label for="RegistrationID">RegistrationID</label>
			                <div class="input-box">
			                      <span><?php echo $currentPaymentPost['txnid'] ?></span>
			                      <br />
   								  <span>Save it for future reference .</span>					
			                </div>
			            </li>
	    		
			            <li>
			            	<label for="PaybleAmount">Payble Amount</label>
			                <div class="input-box">
			                	   <span><?php echo $currentPaymentPost['amount'] ?></span>
			                </div>
			            </li>
			            
			            <li>
			            	<div class="input-box">
			                	   <span style="color: red;"><?php echo "without payment your registration not complete.." ?></span>
			                </div>
			            </li>
			           
			            <li>
			                <input name="TermsAndCondition" value="" id="TermsAndCondition" type="checkbox"> 
			                &nbsp;&nbsp;&nbsp;&nbsp;<span>Accept All Terms And Condition</span>
			            </li>
			            
			            
			        </ul>
			        
			        
			        
			         <input type="hidden" name="key" value="<?php echo $currentPaymentPost['key'] ?>" />
				     <input type="hidden" name="hash" value="<?php echo $currentPaymentPost['hash'] ?>"/>
				     <input type="hidden" name="txnid" value="<?php echo $currentPaymentPost['txnid'] ?>" />
				     
				     <input type="hidden" name="amount" value="<?php echo $currentPaymentPost['amount'] ?>" />
				     <input type="hidden" name="firstname" value="<?php echo $currentPaymentPost['firstname'] ?>"/>
				     <input type="hidden" name="email" value="<?php echo $currentPaymentPost['email'] ?>" />
				     
				     <input type="hidden" name="phone" value="<?php echo $currentPaymentPost['phone'] ?>" />
				     <input type="hidden" name="productinfo" value="<?php echo $currentPaymentPost['productinfo'] ?>"/>
				     <input type="hidden" name="surl" value="<?php echo $currentPaymentPost['surl'] ?>" />
				     
				     <input type="hidden" name="furl" value="<?php echo $currentPaymentPost['furl'] ?>" />
				     <input type="hidden" name="service_provider" value="<?php echo $currentPaymentPost['service_provider'] ?>" />
			         <input type="hidden" name="curl" value="<?php echo $currentPaymentPost['curl'] ?>" />
			        
			     </td>
			   
              </tr>   
        
       </table>
    </div> 	
	
	<div class="buttons-set" style="margin-top: 0px !important; border-top: none !important; border-bottom: 1px solid #E4E4E4 !important; ">
    	<button type="button" title="<?php echo $this->__('Pay') ?>" id="PaymentButton" name="PaymentButton" class="button" onclick="return paymentFormJS.submit() "><span><span><?php echo $this->__('Pay Now') ?></span></span></button>
    </div>

<!--      
</form>

<form>
-->
 

<script type="text/javascript">
//<![CDATA[
           
    var paymentFormObj= new VarienForm('<?php echo $HTMLFormID ?>', true);

    var paymentFormJS = {
    		submit : function(){
    			if(!$('TermsAndCondition').checked){
	             	alert('Please Accept Term And Conditions !');
	             	return false;
				}
        		
        		$('<?php echo $HTMLFormID ?>').submit();
    		}
    };
    	
//]]>
</script>
