<?php
?>
<!--   
<p style="font-size: 14pt;"><strong>Terms and Condition:</strong><p>

<ol>
	<li>You can registration for Robomate+ Scholarship Test through "www.aapnicity.com".</li>
	<li>To reg. online - Find the examination you wish to enter on the relevant examination page & complete all the required information.</li>
	<li>To reg. offline - visit Bhavya Solutions, Shakti Marg, Near Celebration Palace, Sri Ganganagar.</li>
	<li>Helpline -90244-44681</li>
	
	<li>
		In both cases, you must ensure that you provide the following information:
		<ul>
			<li>Your full name - as it appears on your Passport or ID and in the same order</li>
			<li>Address - at the time of registration.</li>
			<li>Place of Instruction - The school/college at which you attend classes.</li>
			<li>Date of Birth</li>
			<li>Aadhar Card and School ID number - These Id you must bring with you on the exam day.</li>
			<li>Nationality</li>
		</ul>	
	</li>
	
	<li>I understand & accept that I must bring the Aadhar card and School Id as recorded on the registration form with me on the test day. If proof of identification is not provided to the Trainer/Invigilator prior to the examination, Trainer/Invigilator reserve the right to refuse the candidate entry to sit the exam.</li>
	<li>Candidates must be present at least 30 minutes prior to the examination start time. When attending the exam, candidates must ensure they are polite and courteous to other candidates and the Trainer/Invigilator.</li>
	
	<li>If you registration online you can pay using a credit or a debit card through Payumoney following the instructions on the website.</li>
	<li>If you book offline, deposit the registration fees advance, Registration confirmation is subject to clear the registration fees .</li>
	<li>Once the Registration completed, registration fee is non-refundable.</li>
	<li>A confirmation of Registration will be e-mailed/sms/call  to candidate.</li>
	<li>Bhavya Solutions, Reserved the all rights and change the any condition without any prior notice.</li>
</ol>
-->
<div class="block block-list block-categories" >
    <div id="block-categories" class="block-center-title active">
        <strong><span id="CustomPageTitle">Terms and Condition:</span></strong>
        <a href="<?php echo $this->getUrl('medicalcamp/Registration_Registration/index') ?>" >&lt;&lt;</a>
    </div>
</div>

<p> 1. You can registration for Robomate+ Scholarship Test through "www.aapnicity.com".</p>
<p> 2. To reg. online - Find the examination you wish to enter on the relevant examination page & complete all the required information.</p>
<p> 3. To reg. offline - visit Bhavya Solutions, Shakti Marg, Near Celebration Palace, Sri Ganganagar.</p>
<p> 4. Helpline -90244-44681</p>

<p> 5. In both cases, you must ensure that you provide the following information:</p>
	
	<div style="margin-left: 10px !important;">
		<p> (a) Your full name - as it appears on your Passport or ID and in the same order</p>
		<p> (b) Address - at the time of registration.</p>
		<p> (c) Place of Instruction - The school/college at which you attend classes.</p>
		<p> (d) Date of Birth</p>
		<p> (e) Aadhar Card and School ID number - These Id you must bring with you on the exam day.</p>
		<p> (f) Nationality</p>
	</div>	


<p>6. I understand & accept that I must bring the Aadhar card and School Id as recorded on the registration form with me on the test day. If proof of identification is not provided to the Trainer/Invigilator prior to the examination, Trainer/Invigilator reserve the right to refuse the candidate entry to sit the exam.</p>
<p>7. Candidates must be present at least 30 minutes prior to the examination start time. When attending the exam, candidates must ensure they are polite and courteous to other candidates and the Trainer/Invigilator.</p>

<p>8. If you registration online you can pay using a credit or a debit card through Payumoney following the instructions on the website.</p>
<p>9. If you book offline, deposit the registration fees advance, Registration confirmation is subject to clear the registration fees .</p>
<p>10. Once the Registration completed, registration fee is non-refundable.</p>
<p>11. A confirmation of Registration will be e-mailed/sms/call  to candidate.</p>
<p>12. Bhavya Solutions, Reserved the all rights and change the any condition without any prior notice.</p>
