<?php
	$HTMLFormID = $this->getHTMLFormID();
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>

            <td style="width:50%;"><h3 class="icon-head head-permissions-role"><?php echo $this->__('Send Email') ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getBackButtonHtml() ?>
                <?php echo $this->getResetButtonHtml() ?>
                <?php echo $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<form action="<?php echo $this->getUrl('*/*/sendEmail') ?>" method="post" id="<?php echo $HTMLFormID;?>">
    <?php echo $this->getBlockHtml('formkey')?>
    <?php echo $this->getEntropy(); ?>
</form>
 


<script type="text/javascript">

function sendEmailVO(){
	this.EmailTemplateID = null;
	this.EmailConfigID = null;
	this.ReceiverEmail = null;
}
var newSendEmailDTO = new sendEmailVO();


var newSendEmailDTO = new sendEmailVO();
var formObj = new varienForm('<?php echo $HTMLFormID; ?>');
var formJS  = {

		submit : function(){
    		if(  !formJS.saveValidation() ) return ;
				formJS.saveAjax();
		},

		saveValidation : function(){
			var errorMsg = '';
         	if( !(formObj.validator && formObj.validator.validate())  ){
    	    	return false;
	    	}

         	newSendEmailDTO.EmailTemplateID = $('EmailTemplateID').value.strip();
			newSendEmailDTO.EmailConfigID = $('EmailConfigID').value.strip();
			newSendEmailDTO.ReceiverEmail = $('ReceiverEmail').value.strip();
		
			if(newSendEmailDTO.EmailTemplateID == null || newSendEmailDTO.EmailTemplateID == ''){
				errorMsg += "=> Please Select Email Template ! \n";
			}
			
			if(newSendEmailDTO.EmailConfigID == null || newSendEmailDTO.EmailConfigID == ''){
				errorMsg += "=> Please Select Sender Email ! \n";
			}

			if(newSendEmailDTO.ReceiverEmail == null || newSendEmailDTO.ReceiverEmail == ''){
				errorMsg += "=> Please Enter User Email ! \n";
			}else{
				var emailString = newSendEmailDTO.ReceiverEmail;
				var emailArray  = emailString.split(',');
				for(count=0; count<emailArray.length; count++){
					var email = emailArray[count];
					if(email == null || email == ''){
						errorMsg += "=> Please Remove comma(,) from end ! \n";
					}else if(!(Validate.isEmailValid(email)) ){
						errorMsg += "=> Invalid Email=> "+email+" ! \n";
					}
				}
			}
			
			if(errorMsg != ''){
            	alert(errorMsg);
				return false;
			}
			return true;
		},


		saveAjax: function(){
        	var URL = "<?php echo $this->getUrl('*/Email_SendEmail_SendEmail/sendEmail')?>" ;
		    var parameters= {"SendEmailDataObj": JSON.stringify(newSendEmailDTO,null) };
		    var callBackMethod ="formJS.responseSave";
		    var callBackArgs =null;

		    if(confirm("Are you sure you want to send email to selected listing(s)?") == true){
		    	ajaxRequest.execute(URL, parameters, callBackMethod , callBackArgs );
		    }else{
				return false;
			}
		    
     	},

     	
	    responseSave : function(response,args) {
	     	var msg = new Array();
        	if(response.SuccessMessage !=null){
			 	msg[0] = response.SuccessMessage;
			 	MESSAGEHANDLER.successMessagePublish(msg, $('messages'));
			 	return;
			}else if(response.ErrorMessage !=null){
				msg[0] = response.ErrorMessage;
				MESSAGEHANDLER.errorMessagePublish(msg, $('messages'));
    			return false;
 			}
 	 	}
		
		 
};
 
</script>