<?php
    $HTMLFormID = $this->getHTMLFormID();
    $serviceVO = $this->getServiceVO();
    $statusOptions  = $this->getStatusOptions();
    $entityOptions  = $this->getEntityOptions();
    
    
    if($serviceVO == null){
    	$serviceVO = new Margshri_WebPortal_VO_Master_SubPage_ServiceVO();
    }
?>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Sub Page Service</h4>
		<div class="form-buttons"></div>
	</div>

	<div class="fieldset " id="base_fieldset">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
				
					<tr>
						<td class="label">
							<label for="Value">Name<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="Value" id="Value" 
							value="<?php echo $serviceVO->getValue() ?>" 
							class="required-entry input-text" />
						</td>
					</tr>

					<tr>
						<td class="label">
							<label for="Code">Code<span class="required">*</span></label>
						</td>
						<td class="value">
							<input type="text" name="Code" id="Code" 
							value="<?php echo $serviceVO->getCode() ?>" 
							class="required-entry input-text" />
						</td>
					</tr>
					
					<tr>
						<td class="value" colspan="2">
							<div style="border: 1px solid; border-color: #AAA #C8C8C8 #C8C8C8 #AAA;">
								<img id="Preview" alt="Image" src="<?php echo ($serviceVO->getImageURL() != null &&  $serviceVO->getImageURL() != '' )  ?  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $serviceVO->getImageURL() : '' ?>"  width="487px" height="162px" style="border-style: hidden;"/>
								<input type="file" id="Image" name="Image" onchange="return formJS.getFilePath()" style="display: none;" />
						   	</div>
					   	</td>
					</tr>
					
					<tr>
						<td class="value" colspan="2" style="text-align: right;">
							<button type="button" id="Browse" name="Browse" onclick="return formJS.browseImageFile()" >Browse</button>
						</td>
					</tr> 
					
					<!--  
					<tr>
						<td class="label">
							<label for="EntityID">Entity<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="EntityID" id="EntityID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($entityOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($serviceVO->getEntityID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
						</td>
					</tr>
					-->
					
					
					<tr>
						<td class="label">
							<label for="StatusID">Status<span class="required">*</span></label>
						</td>
						<td class="value">
							<select name="StatusID" id="StatusID" class="validate-select">
								<option value="">--Select--</option>
								<?php foreach ($statusOptions as $key=>$value): ?>
									<option value="<?php echo $key ?>" <?php echo ($serviceVO->getStatusID() == $key) ? 'Selected="Selected"' : '' ?> ><?php echo $value ?></option>	
								<?php endforeach; ?>
							</select>
							
							<input type="hidden" id="ID" name="ID" value="<?php echo ($serviceVO->getID() > 0) ? $serviceVO->getID() : 0 ?>" />
						</td>
					</tr>
					
				</tbody>
			</table>
				
				 
		</div>
	</div>
</div>