<?php
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-permissions-role"><?php echo $this->__("Society-List") ?></h3></td>
            <td class="form-buttons">
            <?php if(Margshri_Helper_Utility::isACLAllowed("admin/smss/society/add")): ?>
            	<button class="scalable add" onclick="window.location='<?php echo $this->getAddNewUrl() ?>'"><span><?php echo $this->__('Add New Society') ?></span></button>
            <?php endif; ?>
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getGridHtml() ?>
